---
- name: MongoDB Setup
  hosts: database
  become: true
  gather_facts: true
  vars:
    mongodb_version: "6.0"
    
  tasks:
    - name: Add MongoDB GPG key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
        state: present

    - name: Add MongoDB repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
        state: present
        filename: mongodb-org-{{ mongodb_version }}

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Configure MongoDB to listen on all interfaces
      lineinfile:
        path: /etc/mongod.conf
        regexp: '  bindIp:'
        line: '  bindIp: 0.0.0.0'
        backup: yes

    - name: Start and enable MongoDB
      systemd:
        name: mongod
        state: started
        enabled: yes

    - name: Wait for MongoDB to be ready
      wait_for:
        port: 27017
        delay: 10
