---
- name: Install ArangoDB
  hosts: all
  vars:
    proxy_url: "http://10.1.38.2:3128"
    ansible_ssh_retries: 5
  become: true
  pre_tasks:
    - name: Wait for SSH to be ready
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Set up proxy for connection
      set_fact:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
      delegate_to: localhost

  tasks:
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Install required packages
      apt:
        name:
          - gnupg
          - curl
          - apt-transport-https
        state: present
        update_cache: yes
      retries: "{{ ansible_ssh_retries }}"
      delay: 10

    - name: Add ArangoDB GPG key
      apt_key:
        url: https://download.arangodb.com/arangodb312/DEBIAN/Release.key
        state: present
      retries: "{{ ansible_ssh_retries }}"
      delay: 10

    - name: Add ArangoDB repository
      apt_repository:
        repo: "deb https://download.arangodb.com/arangodb312/DEBIAN/ /"
        state: present
        filename: arangodb
      retries: "{{ ansible_ssh_retries }}"
      delay: 10

    - name: Update apt cache
      apt:
        update_cache: yes
      retries: "{{ ansible_ssh_retries }}"
      delay: 10

    - name: Install ArangoDB
      apt:
        name: arangodb3
        state: present
      retries: "{{ ansible_ssh_retries }}"
      delay: 10

    - name: Enable and start ArangoDB service
      systemd:
        name: arangodb3
        enabled: yes
        state: started
      retries: "{{ ansible_ssh_retries }}"
      delay: 10
