---
- name: Install Coolify
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"

  tasks:
    # Common proxy environment configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Configure Docker proxy
    - name: Create Docker systemd directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

    - name: Configure Docker service with proxy
      copy:
        content: |
          [Service]
          Environment="HTTP_PROXY={{ proxy_url }}"
          Environment="HTTPS_PROXY={{ proxy_url }}"
          Environment="NO_PROXY=localhost,127.0.0.1,172.17.0.0/16"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        mode: '0644'

    - name: Create Docker config directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon with proxy and settings
      copy:
        content: |
          {
            "dns": ["8.8.8.8", "8.8.4.4"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "proxies": {
              "http-proxy": "{{ proxy_url }}",
              "https-proxy": "{{ proxy_url }}",
              "no-proxy": "localhost,127.0.0.1,172.17.0.0/16"
            },
            "storage-driver": "overlay2",
            "ipv6": false
          }
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    # Debug Docker configuration
    - name: Check Docker status
      command: systemctl status docker
      register: docker_status
      ignore_errors: yes

    - name: Display Docker status
      debug:
        var: docker_status.stdout_lines

    - name: Check Docker info
      command: docker info
      register: docker_info
      ignore_errors: yes

    - name: Display Docker info
      debug:
        var: docker_info.stdout_lines

    - name: Test Docker pull
      command: docker pull hello-world
      register: docker_pull_test
      ignore_errors: yes

    - name: Display Docker pull test results
      debug:
        var: docker_pull_test

    # Download and install Coolify with debugging
    - name: Download Coolify install script
      get_url:
        url: https://cdn.coollabs.io/coolify/install.sh
        dest: /tmp/coolify_install.sh
        mode: '0755'
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Display Coolify script content
      command: cat /tmp/coolify_install.sh
      register: script_content

    - name: Show script content
      debug:
        var: script_content.stdout_lines

    - name: Execute Coolify install script with debug
      shell: bash -x /tmp/coolify_install.sh
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
        HTTP_PROXY: "{{ proxy_url }}"
        HTTPS_PROXY: "{{ proxy_url }}"
        DOCKER_HTTP_PROXY: "{{ proxy_url }}"
        DOCKER_HTTPS_PROXY: "{{ proxy_url }}"
      register: coolify_install

    - name: Display Coolify installation output
      debug:
        var: coolify_install

    - name: Clean up installation files
      file:
        path: /tmp/coolify_install.sh
        state: absent
