---
- name: Install Coolify
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"

  tasks:
    # Common proxy environment configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Configure Docker
    - name: Create Docker config directory
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: Configure Docker daemon
      copy:
        content: |
          {
            "default-address-pools": [
              {
                "base": "172.17.0.0/16",
                "size": 24
              }
            ],
            "dns": ["8.8.8.8", "8.8.4.4"],
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            },
            "proxies": {
              "http-proxy": "{{ proxy_url }}",
              "https-proxy": "{{ proxy_url }}",
              "no-proxy": "localhost,127.0.0.1"
            }
          }
        dest: /etc/docker/daemon.json
        mode: '0644'

    - name: Create Docker systemd override directory
      file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        mode: '0755'

    - name: Configure Docker service proxy
      copy:
        content: |
          [Service]
          Environment="HTTP_PROXY={{ proxy_url }}"
          Environment="HTTPS_PROXY={{ proxy_url }}"
          Environment="NO_PROXY=localhost,127.0.0.1,172.17.0.0/16"
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted

    # Create required directories
    - name: Create Coolify directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      with_items:
        - /data/coolify/source
        - /data/coolify/ssh
        - /data/coolify/applications
        - /data/coolify/databases
        - /data/coolify/backups
        - /data/coolify/services
        - /data/coolify/proxy
        - /data/coolify/webhooks-during-maintenance
        - /data/coolify/sentinel
        - /data/coolify/ssh/keys
        - /data/coolify/ssh/mux
        - /data/coolify/proxy/dynamic

    - name: Set proper ownership
      file:
        path: /data/coolify
        owner: '9999'
        group: root
        recurse: yes

    # Install Coolify
    - name: Download Coolify install script
      get_url:
        url: https://cdn.coollabs.io/coolify/install.sh
        dest: /tmp/coolify_install.sh
        mode: '0755'
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Execute Coolify install script
      shell: bash /tmp/coolify_install.sh
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
        HTTP_PROXY: "{{ proxy_url }}"
        HTTPS_PROXY: "{{ proxy_url }}"
      register: coolify_install

    - name: Display Coolify installation output
      debug:
        var: coolify_install.stdout_lines

    - name: Clean up installation files
      file:
        path: /tmp/coolify_install.sh
        state: absent

    - name: Print installation complete message
      debug:
        msg: "Coolify has been installed successfully. Access it at http://{{ ansible_host }}:8000"
