---
- hosts: all
  become: yes
  vars:
    edb_version: 17
    dns_server: 8.8.8.8

  tasks:
    # DNS configuration for both Ubuntu and RHEL
    - name: Configure resolv.conf with Google DNS (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
      args:
        warn: false  # Disable warnings about using shell instead of copy module
    
    - name: Configure resolv.conf with Google DNS (RHEL)
      when: ansible_os_family == "RedHat"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
      args:
        warn: false  # Disable warnings about using shell instead of copy module

    - name: Ensure resolv.conf permissions are correct
      file:
        path: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Clear APT proxy configuration
      copy:
        content: ""
        dest: /etc/apt/conf.d/90curtin-aptproxy
        force: yes
        mode: 0644
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache for Ubuntu
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Update package cache for RHEL
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Install required dependencies (Ubuntu)
      apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install required dependencies (RHEL)
      yum:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present
      when: ansible_os_family == "RedHat"

    - name: Download EDB repository setup script
      get_url:
        url: "https://downloads.enterprisedb.com/ODhIpQiBGQejsnFtPvwMH6cslBPSS2V9/enterprise/setup.deb.sh"
        dest: /tmp/edb_setup.sh
        mode: 0755
      register: edb_script_download
      when: ansible_distribution == "Ubuntu"

    - name: Execute EDB repository setup script (Ubuntu)
      command: /tmp/edb_setup.sh
      args:
        creates: /etc/apt/sources.list.d/edb.list
      register: edb_repo_setup
      when: ansible_distribution == "Ubuntu"

    - name: Install EDB Advanced Server (Ubuntu)
      apt:
        name: "edb-as{{ edb_version }}-server"
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Remove temporary setup script
      file:
        path: /tmp/edb_setup.sh
        state: absent
      when: ansible_distribution == "Ubuntu"

  post_tasks:
    - name: Verify EDB installation
      command: psql -V
      register: psql_version
      changed_when: false
      ignore_errors: yes

    - name: Display EDB version
      debug:
        var: psql_version.stdout_lines
      when: psql_version.rc == 0
