---
- name: Install Coolify
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"

  tasks:
    # Common proxy configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ubuntu-specific tasks
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # RHEL-specific tasks
    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == "RedHat"
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    # Install required packages
    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - curl
          - wget
          - git
          - jq
          - openssl
          - docker.io
        state: present

    - name: Install required packages (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name:
          - curl
          - wget
          - git
          - jq
          - openssl
          - docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /coolify
        - /coolify/data

    - name: Execute Coolify installation
      shell: |
        export http_proxy="{{ proxy_url }}"
        export https_proxy="{{ proxy_url }}"
        bash /tmp/coolify_install.sh --non-interactive
      args:
        executable: /bin/bash
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
      async: 1800  # 30 minutes timeout
      poll: 30     # Check every 30 seconds

    - name: Wait for Coolify to be available
      wait_for:
        port: 8000
        timeout: 300
        delay: 10

    - name: Print installation complete message
      debug:
        msg: "Coolify has been installed successfully. Access it at https://{{ morpheus['server']['internalIp'] }}:8000"
