---
- name: Install cPanel
  hosts: all
  become: true
  gather_facts: true
  vars:
    cpanel_url: "https://securedownloads.cpanel.net/latest"
    rhel_username: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelEmail'] | default('') }}"
    rhel_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelPw'] | default('') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"
    proxy_url: "http://10.1.38.2:3128"

  tasks:
    - name: Configure HTTP proxy for yum (RHEL)
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes
      when: ansible_os_family == 'RedHat'
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'
        
    # RHEL-specific tasks
    - name: Register and subscribe RHEL system
      when: ansible_os_family == 'RedHat'
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == 'RedHat'
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    # System prerequisites
    - name: Update package cache (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        update_cache: yes

    - name: Install prerequisites (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name:
          - perl
          - gcc
          - gcc-c++
          - kernel-devel
          - make
          - wget
          - tar
        state: present

    # Common preparation tasks
    - name: Check if cPanel is already installed
      stat:
        path: /usr/local/cpanel
      register: cpanel_check

    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Update hosts file
      lineinfile:
        path: /etc/hosts
        line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
        regexp: "^{{ ansible_default_ipv4.address }}"
        state: present

    # cPanel installation
    - name: Download cPanel installation script
      when: not cpanel_check.stat.exists
      get_url:
        url: "{{ cpanel_url }}"
        dest: /home/latest
        mode: '0755'

    - name: Run cPanel installation
      when: not cpanel_check.stat.exists
      shell: |
        cd /home && 
        ./latest
      async: 3600
      poll: 30

    # Firewall configuration
    - name: Configure firewall for cPanel (RHEL)
      when: ansible_os_family == 'RedHat'
      shell: |
        firewall-cmd --permanent --add-service=cpanel
        firewall-cmd --permanent --add-service=cpanel-webmail
        firewall-cmd --permanent --add-service=whostmgrd
        firewall-cmd --permanent --add-port=2082-2083/tcp
        firewall-cmd --permanent --add-port=2095-2096/tcp
        firewall-cmd --permanent --add-port=2077-2078/tcp
        firewall-cmd --reload
      ignore_errors: yes

    - name: Clean up installation files
      file:
        path: /home/latest
        state: absent
      ignore_errors: yes

    - name: Wait for cPanel to be accessible
      wait_for:
        port: 2082
        timeout: 300
      ignore_errors: yes

    - name: Print cPanel installation complete message
      debug:
        msg: |
          cPanel has been installed successfully.
          WHM (WebHost Manager) can be accessed at: https://{{ morpheus['server']['internalIp'] }}:2087
          cPanel can be accessed at: https://{{ morpheus['server']['internalIp'] }}:2083
