---
- name: Install cPanel
  hosts: all
  become: true
  gather_facts: true
  vars:
    cpanel_url: "https://securedownloads.cpanel.net/latest"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"
    proxy_url: "http://10.1.38.2:3128"
  tasks:
    # Proxy configuration (your existing tasks)
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ubuntu-specific tasks
    - name: Update package cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install prerequisites (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - perl
          - curl
        state: present


    - name: Set hostname
      hostname:
        name: "{{ inventory_hostname }}"
      when: ansible_distribution == "Ubuntu"

    # cPanel installation
    - name: Install cPanel
      shell: "cd /home && wget -e use_proxy=yes -e http_proxy={{ proxy_url }} -e https_proxy={{ proxy_url }} --no-check-certificate -O latest {{ cpanel_url }} && sh latest"
      args:
        creates: /usr/local/cpanel
      register: cpanel_install

    - name: Print cPanel installation complete message
      debug:
        msg: |
          cPanel has been installed successfully.
          WHM (WebHost Manager) can be accessed at: https://{{ morpheus['server']['internalIp'] }}:2087
          cPanel can be accessed at: https://{{ morpheus['server']['internalIp'] }}:2083
