---
- name: Install Docker
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
  tasks:
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set up the Docker repository
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Update apt cache (again)
      apt:
        update_cache: yes

    - name: Debug - List available Docker packages
      shell: apt-cache search docker-ce
      register: docker_packages

    - name: Display available Docker packages
      debug:
        var: docker_packages.stdout_lines

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
      register: docker_install_result
      ignore_errors: yes

    - name: Display Docker installation result
      debug:
        var: docker_install_result

    - name: Configure Docker daemon proxy
      copy:
        content: |
          {
            "proxies": {
              "default": {
                "httpProxy": "{{ proxy_url }}",
                "httpsProxy": "{{ proxy_url }}"
              }
            }
          }
        dest: /etc/systemd/system/docker.service.d/proxy.conf
        mode: '0644'
      notify:
        - Restart Docker

    - name: Configure Docker DNS
      copy:
        content: |
          {
            "dns": ["8.8.8.8", "8.8.4.4"]
          }
        dest: /etc/docker/daemon.json
      notify:
        - Restart Docker

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes
      when: docker_install_result is success

    - name: Verify Docker installation
      command: docker run hello-world
      register: hello_world_output
      changed_when: false
      when: docker_install_result is success

    - name: Display Docker verification result
      debug:
        var: hello_world_output.stdout_lines
      when: docker_install_result is success

  handlers:
    - name: Restart Docker
      systemd:
        name: docker
        state: restarted
