---
- name: Install Basic Drupal on Ubuntu
  hosts: all
  become: true
  gather_facts: true
  vars:
    php_version: "8.1"
    drupal_version: "10.4.2"
    web_root: "/var/www/html"
    mysql_root_password: "RootRoot"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    # Basic system setup
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Install required packages
    - name: Install essential packages
      apt:
        name:
          - apache2
          - mysql-server
          - php{{ php_version }}
          - php{{ php_version }}-mysql
          - php{{ php_version }}-gd
          - php{{ php_version }}-xml
          - php{{ php_version }}-mbstring
          - unzip
          - wget
        state: present

    # Configure MySQL with basic settings
    - name: Start MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    # Set MySQL root password
    - name: Set MySQL root password
      shell: |
        mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
      ignore_errors: true

    # Create database and user
    - name: Create Drupal database and user
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "
        CREATE DATABASE IF NOT EXISTS drupal;
        CREATE USER IF NOT EXISTS 'drupal'@'localhost' IDENTIFIED BY 'drupalpass';
        GRANT ALL PRIVILEGES ON drupal.* TO 'drupal'@'localhost';
        FLUSH PRIVILEGES;"
      ignore_errors: true

    # Install Drupal
    - name: Download and extract Drupal
      unarchive:
        src: "https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
        dest: "{{ web_root }}"
        remote_src: yes
        creates: "{{ web_root }}/drupal"

    - name: Set permissions
      file:
        path: "{{ web_root }}"
        owner: www-data
        group: www-data
        recurse: yes

    - name: Start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Display MySQL version
      command: mysql --version
      register: mysql_version
      changed_when: false

    - name: Display completion message
      debug:
        msg: |
          Drupal installation ready!
          Visit http://{{ morpheus['server']['internalIp'] }} to complete setup
          
          Database details:
          Name: drupal
          User: drupal
          Password: drupalpass
          
          MySQL version: {{ mysql_version.stdout }}
