---
- name: Install Basic Drupal on Ubuntu
  hosts: all
  become: true
  gather_facts: true
  vars:
    php_version: "8.1"
    drupal_version: "10.4.2"
    web_root: "/var/www/html"
    mysql_root_password: "ACSCloud!2021!"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"
    
  tasks:
    # Basic system setup
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Install minimum required packages
    - name: Install essential packages
      apt:
        name:
          - apache2
          - mysql-server
          - php{{ php_version }}
          - php{{ php_version }}-mysql
          - php{{ php_version }}-gd
          - php{{ php_version }}-xml
          - php{{ php_version }}-mbstring
          - unzip
          - wget
        state: present

    # Configure MySQL with basic settings
    - name: Start MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    # Set MySQL root password using the pattern from reference
    - name: Set MySQL root password
      shell: |
        mysql --user=root --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
      ignore_errors: true

    # Create database and user using direct MySQL commands
    - name: Create Drupal database and user
      shell: |
        mysql -u root -p{{ mysql_root_password }} -e "
        CREATE DATABASE IF NOT EXISTS drupal;
        CREATE USER IF NOT EXISTS 'drupal'@'localhost' IDENTIFIED BY 'ACSCloud!2021!';
        GRANT ALL PRIVILEGES ON drupal.* TO 'drupal'@'localhost';
        FLUSH PRIVILEGES;"
      ignore_errors: true

    # Clear web root and prepare for Drupal
    - name: Remove default web content
      file:
        path: "{{ web_root }}"
        state: absent

    - name: Create fresh web root
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    # Install Drupal
    - name: Download Drupal
      get_url:
        url: "https://ftp.drupal.org/files/projects/drupal-{{ drupal_version }}.tar.gz"
        dest: "/tmp/drupal.tar.gz"

    - name: Extract Drupal
      unarchive:
        src: "/tmp/drupal.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Drupal files to web root
      shell: "cp -r /tmp/drupal-{{ drupal_version }}/* {{ web_root }}/"

    - name: Set proper permissions
      shell: |
        chown -R www-data:www-data {{ web_root }}
        find {{ web_root }} -type d -exec chmod 755 {} \;
        find {{ web_root }} -type f -exec chmod 644 {} \;
    
    # Modified Apache Configuration Section
    - name: Enable Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - rewrite
        - env
        - dir
        - mime
    
    - name: Configure Apache for Drupal
      copy:
        content: |
          <VirtualHost *:80>
            ServerAdmin webmaster@localhost
            DocumentRoot {{ web_root }}
            
            <Directory {{ web_root }}>
              Options FollowSymLinks
              AllowOverride All
              Require all granted
            </Directory>
            
            ErrorLog ${APACHE_LOG_DIR}/error.log
            CustomLog ${APACHE_LOG_DIR}/access.log combined
          </VirtualHost>
        dest: /etc/apache2/sites-available/000-default.conf
    
    - name: Ensure .htaccess exists and has correct permissions
      copy:
        remote_src: yes
        src: "{{ web_root }}/.htaccess.txt"
        dest: "{{ web_root }}/.htaccess"
        owner: www-data
        group: www-data
        mode: '0644'
      ignore_errors: yes
    
    - name: Create settings.php from default
      copy:
        remote_src: yes
        src: "{{ web_root }}/sites/default/default.settings.php"
        dest: "{{ web_root }}/sites/default/settings.php"
        owner: www-data
        group: www-data
        mode: '0644'
    
    - name: Create files directory
      file:
        path: "{{ web_root }}/sites/default/files"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
    
    - name: Verify Apache configuration
      shell: apache2ctl -t
      register: apache_verify
      
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
        enabled: yes
      when: apache_verify.rc == 0
            
    - name: Display completion message
      debug:
        msg: |
          Drupal installation ready!
          Visit http://{{ morpheus['server']['internalIp'] }} to complete setup
          
          Database details:
          Name: drupal
          User: drupal
          Password: ACSCloud!2021!
          
          MySQL version: {{ mysql_version.stdout }}
