---
- name: Install Elasticsearch Stack
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    elastic_version: "8.x"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"

  tasks:
    # Common proxy environment configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ubuntu-specific tasks
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - apt-transport-https
          - gpg
          - curl
        state: present
        update_cache: yes

    - name: Download Elasticsearch GPG key (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: |
        curl -x {{ proxy_url }} -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg

    - name: Add Elasticsearch repository (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/{{ elastic_version }}/apt stable main" | tee /etc/apt/sources.list.d/elastic-{{ elastic_version }}.list

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    # RHEL-specific tasks
    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == "RedHat"
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Download Elasticsearch repository file (RHEL)
      when: ansible_os_family == "RedHat"
      get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /etc/pki/rpm-gpg/GPG-KEY-elasticsearch
        mode: '0644'
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Add Elasticsearch repository (RHEL)
      when: ansible_os_family == "RedHat"
      yum_repository:
        name: elasticsearch-{{ elastic_version }}
        description: Elasticsearch repository for {{ elastic_version }} packages
        baseurl: https://artifacts.elastic.co/packages/{{ elastic_version }}/yum
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/GPG-KEY-elasticsearch
        enabled: yes

    # Common installation tasks
    - name: Install Elasticsearch
      package:
        name: elasticsearch
        state: present

    - name: Install Kibana
      package:
        name: kibana
        state: present

    - name: Install Logstash
      package:
        name: logstash
        state: present

    - name: Configure Kibana
      lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^server\.host:'
        line: 'server.host: "0.0.0.0"'
        create: yes

    - name: Create Elasticsearch systemd directory
      file:
        path: /etc/systemd/system/elasticsearch.service.d
        state: directory
        mode: '0755'

    - name: Configure Elasticsearch service with proxy
      copy:
        content: |
          [Service]
          Environment="HTTP_PROXY={{ proxy_url }}"
          Environment="HTTPS_PROXY={{ proxy_url }}"
          Environment="NO_PROXY=localhost,127.0.0.1"
        dest: /etc/systemd/system/elasticsearch.service.d/http-proxy.conf
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Elasticsearch
      systemd:
        name: elasticsearch
        state: started
        enabled: yes

    - name: Start and enable Kibana
      systemd:
        name: kibana
        state: started
        enabled: yes

    - name: Start and enable Logstash
      systemd:
        name: logstash
        state: started
        enabled: yes

    - name: Wait for Elasticsearch to start
      wait_for:
        port: 9200
        delay: 10
        timeout: 300

    - name: Generate Elastic password
      shell: |
        cd /usr/share/elasticsearch && ./bin/elasticsearch-reset-password -u elastic --batch
      register: elastic_password
      changed_when: false

    - name: Generate Kibana enrollment token
      shell: |
        cd /usr/share/elasticsearch && ./bin/elasticsearch-create-enrollment-token -s kibana
      register: kibana_token
      changed_when: false

    - name: Display Elastic password
      debug:
        var: elastic_password.stdout_lines

    - name: Display Kibana enrollment token
      debug:
        var: kibana_token.stdout_lines

    - name: Print installation complete message
      debug:
        msg: "Elasticsearch Stack has been installed successfully. Access Kibana at http://localhost:5601"
