---

- name: firewall example files
  hosts: unassigned
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: log value of f5
      debug:
        msg: "{{ morpheus['customOptions']['f5'] }}"
        
    
