---

- name: firewall example files
  hosts: unassigned
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
    - name: Create and write to f5.txt
      debug:
        msg: "f5 is {{ morpheus['customOptions']['f5'] }}"

    - lineinfile:
        path: /tmp/f5
        line: test
        create: yes

    - name: Create and write to palo.txt
      copy:
        content: "test {{ morpheus['customOptions']['palo'] }}"
        dest: "/tmp/palo.txt"

    - name: Create and write to forti.txt
      copy:
        content: "{{ morpheus['customOptions']['forti'] }}"
        dest: "/tmp/forti.txt"

    - name: Create and write to nsx.txt
      copy:
        content: "{{ morpheus['customOptions']['nsx'] }}"
        dest: "/tmp/nsx.txt"
        
    
