---

- name: firewall example files
  hosts: unassigned
  become: true
  #gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks: 
  
    - name: Create and write to f5.txt
      copy:
        content: "test"
        dest: "/tmp/f5.txt"

    - name: Create and write to palo.txt
      copy:
        content: "test"
        dest: "/tmp/palo.txt"

    - name: Create and write to forti.txt
      copy:
        content: "test"
        dest: "/tmp/forti.txt"

    - name: Create and write to nsx.txt
      copy:
        content: "firewall_test"
        dest: "/tmp/nsx.txt"
        
    
