- name: Installation de Hadoop en mode Pseudo-distribué
  hosts: all
  become: yes
  tasks:

    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Créer un utilisateur Hadoop
      user:
        name: hadoop
        shell: /bin/bash
        createhome: yes

    - name: Télécharger Hadoop (avant-dernière version)
      get_url:
        url: "https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6.tar.gz"
        dest: "/home/hadoop/hadoop-3.3.6.tar.gz"
        mode: '0644'
        owner: hadoop
        group: hadoop

    - name: Extraire Hadoop
      unarchive:
        src: "/home/hadoop/hadoop-3.3.6.tar.gz"
        dest: "/home/hadoop/"
        remote_src: yes
        owner: hadoop
        group: hadoop

    - name: Renommer le dossier Hadoop
      command: mv /home/hadoop/hadoop-3.3.6 /home/hadoop/hadoop
      args:
        creates: /home/hadoop/hadoop

    - name: Définir les permissions sur Hadoop
      file:
        path: "/home/hadoop/hadoop"
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'

    - name: Ajouter les variables d'environnement Hadoop
      lineinfile:
        path: /home/hadoop/.bashrc
        line: |
          export HADOOP_HOME=/home/hadoop/hadoop
          export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
          export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
          export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      become_user: hadoop

    - name: Générer une clé SSH pour Hadoop
      command: "ssh-keygen -t rsa -N '' -f /home/hadoop/.ssh/id_rsa"
      args:
        creates: /home/hadoop/.ssh/id_rsa
      become_user: hadoop

    - name: Copier la clé publique dans authorized_keys
      copy:
        src: "/home/hadoop/.ssh/id_rsa.pub"
        dest: "/home/hadoop/.ssh/authorized_keys"
        remote_src: yes
        owner: hadoop
        group: hadoop
        mode: '0600'
