---
- name: Install Kubernetes using kURL
  hosts: all
  become: yes
  tasks:
    - name: Configure resolv.conf with Google DNS
      shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: Install required packages
      apt:
        name: 
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    - name: Install Kubernetes with kURL
      shell: curl -fsSL https://kurl.sh/2de1df0 | bash

    - name: Create .kube directory
      file:
        path: /root/.kube
        state: directory
        mode: '0755'

    - name: Copy admin.conf to .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes
        mode: '0600'

    - name: Set KUBECONFIG environment variable
      lineinfile:
        path: /root/.bashrc
        line: 'export KUBECONFIG=/root/.kube/config'
        state: present
