---
- hosts: all
  become: yes
  vars:
    edb_version: 17
    dns_server: 8.8.8.8

  pre_tasks:
    - name: Ensure APT configuration directory exists
      file:
        path: /etc/apt/conf.d
        state: directory
        mode: 0755
        owner: root
        group: root

  tasks:
    - name: Clear APT proxy configuration
      copy:
        content: ""
        dest: /etc/apt/conf.d/90curtin-aptproxy
        force: yes
        mode: 0644

    - name: Verify APT configuration file creation
      stat:
        path: /etc/apt/conf.d/90curtin-aptproxy
      register: apt_proxy_file

    - name: Fail if APT proxy configuration file was not created
      fail:
        msg: "Failed to create APT proxy configuration file"
      when: not apt_proxy_file.stat.exists

    - name: Configure DNS server
      copy:
        content: "nameserver {{ dns_server }}"
        dest: /etc/resolv.conf
        force: yes
        mode: 0644

    - name: Update APT package cache
      apt:
        update_cache: yes
      register: apt_update
      until: apt_update is success
      retries: 3
      delay: 5

    - name: Install required dependencies
      apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present

    - name: Download EDB repository setup script
      get_url:
        url: "https://downloads.enterprisedb.com/ODhIpQiBGQejsnFtPvwMH6cslBPSS2V9/enterprise/setup.deb.sh"
        dest: /tmp/edb_setup.sh
        mode: 0755
        timeout: 60
      register: edb_script_download
      until: edb_script_download is success
      retries: 3
      delay: 5

    - name: Execute EDB repository setup script
      command: /tmp/edb_setup.sh
      args:
        creates: /etc/apt/sources.list.d/edb.list
      register: edb_repo_setup
      failed_when: edb_repo_setup.rc != 0

    - name: Install EDB Advanced Server
      apt:
        name: "edb-as{{ edb_version }}-server"
        state: present
      register: edb_install
      until: edb_install is success
      retries: 3
      delay: 5

    - name: Remove temporary setup script
      file:
        path: /tmp/edb_setup.sh
        state: absent

  post_tasks:
    - name: Verify EDB installation
      command: psql -V
      register: psql_version
      changed_when: false
      ignore_errors: yes

    - name: Display EDB version
      debug:
        var: psql_version.stdout_lines
      when: psql_version.rc == 0

    - name: Final installation status check
      assert:
        that:
          - edb_repo_setup.rc == 0
          - edb_install is success
        fail_msg: "EDB installation encountered issues"
        success_msg: "EDB installation completed successfully"
