---
- name: Install Hadoop on Ubuntu
  hosts: all
  become: yes
  vars:
    hadoop_version: "3.3.1"
    java_version: "openjdk-11-jdk"
    hadoop_user: "hadoop"
    hadoop_group: "hadoop"

  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_version }}"
        state: present

    - name: Create Hadoop user and group
      user:
        name: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Download Hadoop
      get_url:
        url: "https://downloads.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}-tar.gz"
        dest: /tmp/hadoop-{{ hadoop_version }}.tar.gz

    - name: Extract Hadoop
      unarchive:
        src: /tmp/hadoop-{{ hadoop_version }}.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
        state: present
      with_items:
        - "export HADOOP_HOME=/opt/hadoop-{{ hadoop_version }}"
        - "export PATH=$PATH:$HADOOP_HOME/bin"
        - "export PATH=$PATH:$HADOOP_HOME/sbin"

    - name: Load Hadoop environment variables
      shell: source /etc/profile

    - name: Change ownership of Hadoop directory
      file:
        path: /opt/hadoop-{{ hadoop_version }}
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        state: directory

    - name: Create Hadoop data directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: '0755'
      with_items:
        - "/opt/hadoop-{{ hadoop_version }}/data"
        - "/opt/hadoop-{{ hadoop_version }}/data/hdfs"
        - "/opt/hadoop-{{ hadoop_version }}/data/hdfs/namenode"
        - "/opt/hadoop-{{ hadoop_version }}/data/hdfs/datanode"

    - name: Configure Hadoop core-site.xml
      template:
        src: core-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/core-site.xml

    - name: Configure Hadoop hdfs-site.xml
      template:
        src: hdfs-site.xml.j2
        dest: /opt/hadoop-{{ hadoop_version }}/etc/hadoop/hdfs-site.xml

    - name: Start Hadoop services
      shell: "{{ hadoop_home }}/sbin/start-dfs.sh && {{ hadoop_home }}/sbin/start-yarn.sh"
      args:
        chdir: /opt/hadoop-{{ hadoop_version }}
