---
- name: Install Hadoop on Ubuntu
  hosts: hadoop
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - ssh
          - rsync
          - wget
        state: present
        update_cache: yes

    - name: Create Hadoop group
      group:
        name: hadoop
        state: present

    - name: Create Hadoop user
      user:
        name: hadoop
        group: hadoop
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Download Hadoop
      get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6-aarch64.tar.gz
        dest: /tmp/hadoop.tar.gz

    - name: Extract Hadoop
      unarchive:
        src: /tmp/hadoop.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Create Hadoop symlink
      file:
        src: /usr/local/hadoop-3.3.6
        dest: /usr/local/hadoop
        state: link

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/profile.d/hadoop.sh
        line: "{{ item }}"
        create: yes
      loop:
        - 'export HADOOP_HOME=/usr/local/hadoop'
        - 'export PATH=$PATH:$HADOOP_HOME/bin'
        - 'export PATH=$PATH:$HADOOP_HOME/sbin'

    - name: Ensure environment variables are loaded
      shell: source /etc/profile.d/hadoop.sh

    - name: Create Hadoop directories
      file:
        path: "{{ item }}"
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'
      loop:
        - /usr/local/hadoop/tmp
        - /usr/local/hadoop/logs
        - /usr/local/hadoop/data
        - /usr/local/hadoop/name
        - /usr/local/hadoop/data/datanode

    - name: Configure Hadoop core-site.xml
      template:
        src: templates/core-site.xml.j2
        dest: /usr/local/hadoop/etc/hadoop/core-site.xml

    - name: Configure Hadoop hdfs-site.xml
      template:
        src: templates/hdfs-site.xml.j2
        dest: /usr/local/hadoop/etc/hadoop/hdfs-site.xml

    - name: Configure Hadoop mapred-site.xml
      template:
        src: templates/mapred-site.xml.j2
        dest: /usr/local/hadoop/etc/hadoop/mapred-site.xml

    - name: Configure Hadoop yarn-site.xml
      template:
        src: templates/yarn-site.xml.j2
        dest: /usr/local/hadoop/etc/hadoop/yarn-site.xml

    - name: Format the HDFS NameNode
      command: "/usr/local/hadoop/bin/hdfs namenode -format"
      when: ansible_hostname == 'hadoop'  # Only format on the master node

    - name: Start Hadoop services
      shell: |
        /usr/local/hadoop/sbin/start-dfs.sh
        /usr/local/hadoop/sbin/start-yarn.sh
      async: 10
      poll: 0
