- hosts: localhost
  become: true
  vars:
    hadoop_location: "/root/hadoop-1.2.1-1.x86_64.rpm"
    jdk_location: "/root/jdk-8u171-linux-x64.rpm"
    jdk_software: "jdk-8u171-linux-x64.rpm"
    hadoop_software: "hadoop-1.2.1-1.x86_64.rpm"
    namenode_path: "/nn"
    namenode_ip: "192.168.43.4"
    datanode_path: "/dn"

  tasks:
    - name: "Configurer resolv.conf avec Google DNS"
      shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

    - name: "Supprimer les paramètres proxy d'APT"
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    - name: "Copier JDK sur la machine"
      copy:
        src: "{{ jdk_location }}"
        dest: "/root"

    - name: "Copier Hadoop sur la machine"
      copy:
        src: "{{ hadoop_location }}"
        dest: "/root"

    - name: "Installer JDK"
      yum:
        name: "{{ jdk_location }}"
        state: present
        disable_gpg_check: yes

    - name: "Installer Hadoop"
      shell: "rpm -ivh {{ hadoop_software }} --force"

    - name: "Créer le dossier du namenode"
      file:
        path: "{{ namenode_path }}"
        state: directory
        mode: '0755'

    - name: "Créer le dossier du datanode"
      file:
        path: "{{ datanode_path }}"
        state: directory
        mode: '0755'

    - name: "Configurer hdfs-site.xml"
      copy:
        dest: "/etc/hadoop/hdfs-site.xml"
        content: |
          <?xml version="1.0"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
          <configuration>
            <property>
              <name>dfs.name.dir</name>
              <value>{{ namenode_path }}</value>
            </property>
            <property>
              <name>dfs.data.dir</name>
              <value>{{ datanode_path }}</value>
            </property>
          </configuration>

    - name: "Configurer core-site.xml"
      copy:
        dest: "/etc/hadoop/core-site.xml"
        content: |
          <?xml version="1.0"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
          <configuration>
            <property>
              <name>fs.default.name</name>
              <value>hdfs://{{ namenode_ip }}:9001</value>
            </property>
          </configuration>

    - name: "Désactiver le pare-feu"
      service:
        name: "firewalld"
        state: stopped
        enabled: false

    - name: "Désactiver SELinux"
      ansible.posix.selinux:
        state: disabled

    - name: "Formater le Namenode"
      shell: "echo Y | hadoop namenode -format"

    - name: "Redémarrer les services Hadoop"
      shell: |
        hadoop-daemon.sh stop namenode
        hadoop-daemon.sh start namenode
        hadoop-daemon.sh stop datanode
        hadoop-daemon.sh start datanode
