---
- hosts: all
  become: true
  vars:
    hadoop_location: "/root/hadoop-1.2.1-1.x86_64.rpm"
    jdk_location: "/root/jdk-8u171-linux-x64.rpm"
    jdk_software: "jdk-8u171-linux-x64.rpm"
    hadoop_software: "hadoop-1.2.1-1.x86_64.rpm"
    namenode_path: "/nn"
    namenode_ip: "192.168.43.4"
    datanode_path: "/dn"
    hadoop_user: "hadoop"
    hadoop_password: "ACSCloud!2021!"
  tasks:
    - name: "Create Hadoop user"
      user:
        name: "{{ hadoop_user }}"
        password: "{{ hadoop_password | password_hash('sha512') }}"
        shell: "/bin/bash"
        create_home: yes
      
    - name: "Configure resolv.conf with Google DNS"
      copy:
        dest: "/etc/resolv.conf"
        content: "nameserver 8.8.8.8"
      
    - name: "Clear apt proxy settings"
      file:
        path: "/etc/apt/apt.conf.d/90curtin-aptproxy"
        state: absent
      
    - name: "Copy JDK and Hadoop to Hadoop user home"
      copy:
        src: "{{ item }}"
        dest: "/home/{{ hadoop_user }}/"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      loop:
        - "{{ jdk_location }}"
        - "{{ hadoop_location }}"
      
    - name: "Install JDK"
      yum:
        name: "/home/{{ hadoop_user }}/{{ jdk_software }}"
        state: present
        disable_gpg_check: yes
      become: true
      
    - name: "Install Hadoop"
      shell: "rpm -ivh /home/{{ hadoop_user }}/{{ hadoop_software }} --force"
      become: true
      
    - name: "Create directories for Namenode and Datanode"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      loop:
        - "{{ namenode_path }}"
        - "{{ datanode_path }}"
      
    - name: "Configure hdfs-site.xml"
      template:
        dest: "/etc/hadoop/hdfs-site.xml"
        content: |
          <?xml version="1.0"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
          <configuration>
          <property>
          <name>dfs.name.dir</name>
          <value>{{ namenode_path }}</value>
          </property>
          <property>
          <name>dfs.data.dir</name>
          <value>{{ datanode_path }}</value>
          </property>
          </configuration>
      
    - name: "Configure core-site.xml"
      template:
        dest: "/etc/hadoop/core-site.xml"
        content: |
          <?xml version="1.0"?>
          <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
          <configuration>
          <property>
          <name>fs.default.name</name>
          <value>hdfs://{{ namenode_ip }}:9001</value>
          </property>
          </configuration>
      
    - name: "Disable Firewall and SELinux"
      block:
        - name: "Stop and disable firewalld"
          service:
            name: "firewalld"
            state: stopped
            enabled: no
        - name: "Disable SELinux"
          ansible.posix.selinux:
            state: disabled
      
    - name: "Format the Namenode"
      shell: "echo Y | hadoop namenode -format"
      become: true
      become_user: "{{ hadoop_user }}"
      
    - name: "Start Hadoop Services"
      shell: "hadoop-daemon.sh start namenode && hadoop-daemon.sh start datanode"
      become: true
      become_user: "{{ hadoop_user }}"
