---
- name: Install Kubernetes using kURL
  hosts: all
  become: yes
  tasks:
    # System prerequisites
    - name: Configure resolv.conf with Google DNS
      shell: echo "nameserver 8.8.8.8" > /etc/resolv.conf

    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy

    # Install required packages
    - name: Install required packages
      apt:
        name: 
          - curl
          - apt-transport-https
          - ca-certificates
        state: present
        update_cache: yes

    # Create temporary directory for kURL
    - name: Create temporary directory
      file:
        path: /tmp/kurl
        state: directory
        mode: '0755'

    # Download kURL installer
    - name: Download kURL installer
      get_url:
        url: https://kurl.sh/726730f
        dest: /tmp/kurl/install.sh
        mode: '0755'

    # Run kURL installer
    - name: Install Kubernetes with kURL
      shell: bash /tmp/kurl/install.sh
      args:
        creates: /etc/kubernetes/admin.conf
      register: kurl_result

    # Display installation results
    - name: Show installation output
      debug:
        var: kurl_result.stdout_lines

    # Clean up
    - name: Remove temporary files
      file:
        path: /tmp/kurl
        state: absent

    # Verify installation
    - name: Check kubectl version
      shell: kubectl version --short
      register: kubectl_version
      changed_when: false

    - name: Display kubectl version
      debug:
        var: kubectl_version.stdout_lines
