---
- hosts: all
  become: yes
  vars:
    edb_version: 17
    dns_server: 8.8.8.8

  tasks:
    - name: Clear APT proxy configuration
      copy:
        content: ""
        dest: /etc/apt/conf.d/90curtin-aptproxy
        force: yes

    - name: Configure DNS server
      copy:
        content: "nameserver {{ dns_server }}"
        dest: /etc/resolv.conf
        force: yes

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present

    - name: Download EDB repository setup script
      get_url:
        url: "https://downloads.enterprisedb.com/ODhIpQiBGQejsnFtPvwMH6cslBPSS2V9/enterprise/setup.deb.sh"
        dest: /tmp/edb_setup.sh
        mode: 0755

    - name: Execute EDB repository setup script
      command: /tmp/edb_setup.sh
      args:
        creates: /etc/apt/sources.list.d/edb.list

    - name: Install EDB Advanced Server
      apt:
        name: "edb-as{{ edb_version }}-server"
        state: present

    - name: Remove temporary setup script
      file:
        path: /tmp/edb_setup.sh
        state: absent

  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted

  post_tasks:
    - name: Verify EDB installation
      command: psql -V
      register: psql_version
      changed_when: false
      ignore_errors: yes

    - name: Display EDB version
      debug:
        var: psql_version.stdout_lines
      when: psql_version.rc == 0
