---
- hosts: all
  become: yes
  vars:
    edb_version: 17
    dns_server: 8.8.8.8

  pre_tasks:
    - name: Ensure required packages for APT are installed
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    - name: Check APT configuration
      command: apt-config dump
      register: apt_config
      changed_when: false
      failed_when: false

    - name: Debug APT configuration
      debug:
        var: apt_config.stdout_lines
      when: apt_config.rc == 0

  tasks:
    # DNS configuration for Ubuntu
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver {{ dns_server }} > /etc/resolv.conf
      args:
        executable: /bin/bash

    - name: Ensure resolv.conf permissions are correct
      file:
        path: /etc/resolv.conf
        owner: root
        group: root
        mode: 0644

    - name: Clear APT proxy configuration
      copy:
        content: ""
        dest: /etc/apt/conf.d/90curtin-aptproxy
        force: yes
        mode: 0644

    - name: Update APT package cache with detailed error handling
      block:
        - name: Refresh APT cache
          apt:
            update_cache: yes
            force_apt_get: yes
            cache_valid_time: 0
          register: apt_update
          retries: 3
          delay: 5
          until: apt_update is success
      rescue:
        - name: Check APT lock
          stat:
            path: /var/lib/dpkg/lock
          register: apt_lock

        - name: Remove APT lock if exists
          file:
            path: "{{ item }}"
            state: absent
          loop:
            - /var/lib/dpkg/lock
            - /var/lib/apt/lists/lock
          when: apt_lock.stat.exists

        - name: Force APT cache update after lock removal
          apt:
            update_cache: yes
            force_apt_get: yes

    - name: Install required dependencies
      apt:
        pkg:
          - curl
          - gnupg
          - ca-certificates
        state: present

    - name: Download EDB repository setup script
      get_url:
        url: "https://downloads.enterprisedb.com/ODhIpQiBGQejsnFtPvwMH6cslBPSS2V9/enterprise/setup.deb.sh"
        dest: /tmp/edb_setup.sh
        mode: 0755
      register: edb_script_download

    - name: Execute EDB repository setup script
      command: /tmp/edb_setup.sh
      args:
        creates: /etc/apt/sources.list.d/edb.list
      register: edb_repo_setup

    - name: Install EDB Advanced Server
      apt:
        name: "edb-as{{ edb_version }}-server"
        state: present
      register: edb_install
      retries: 3
      delay: 5
      until: edb_install is success

    - name: Remove temporary setup script
      file:
        path: /tmp/edb_setup.sh
        state: absent

  post_tasks:
    - name: Verify EDB installation
      command: psql -V
      register: psql_version
      changed_when: false
      ignore_errors: yes

    - name: Display EDB version
      debug:
        var: psql_version.stdout_lines
      when: psql_version.rc == 0

  handlers:
    - name: Restart networking
      service:
        name: networking
        state: restarted
