---
- name: Install Hadoop on Ubuntu
  hosts: all
  become: yes
  vars:
    java_version: openjdk-11-jdk
    hadoop_version: 3.3.1
    hadoop_user: hadoop
    hadoop_group: hadoop
    hadoop_install_dir: /usr/local/hadoop
    hadoop_download_url: "https://downloads.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}-tar.gz"
    hadoop_tar: "hadoop-{{ hadoop_version }}-tar.gz"
  
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: "{{ java_version }}"
        state: present

    - name: Create Hadoop group
      group:
        name: "{{ hadoop_group }}"
        state: present

    - name: Create Hadoop user
      user:
        name: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        shell: /bin/bash
        create_home: yes

    - name: Download Hadoop
      get_url:
        url: "{{ hadoop_download_url }}"
        dest: /tmp/{{ hadoop_tar }}

    - name: Extract Hadoop
      unarchive:
        src: /tmp/{{ hadoop_tar }}
        dest: "{{ hadoop_install_dir }}"
        remote_src: yes

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
        state: present
      with_items:
        - "export HADOOP_HOME={{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}"
        - "export PATH=$PATH:$HADOOP_HOME/bin"
        - "export PATH=$PATH:$HADOOP_HOME/sbin"

    - name: Source profile
      shell: source /etc/profile
      args:
        executable: /bin/bash

    - name: Create Hadoop directory structure
      file:
        path: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}/{{ item }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: '0755'
      loop:
        - etc
        - data
        - logs

    - name: Create Hadoop environment configuration file
      copy:
        dest: "{{ hadoop_install_dir }}/hadoop-{{ hadoop_version }}/etc/hadoop/hadoop-env.sh"
        content: |
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: '0644'

    - name: Clean up downloaded files
      file:
        path: /tmp/{{ hadoop_tar }}
        state: absent
