---
- name: Install Hadoop on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - openjdk-11-jdk
          - ssh
          - rsync
          - wget
        state: present
        update_cache: yes

    - name: Create Hadoop group
      group:
        name: hadoop
        state: present

    - name: Create Hadoop user
      user:
        name: hadoop
        group: hadoop
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Download Hadoop
      get_url:
        url: https://downloads.apache.org/hadoop/common/hadoop-3.3.6/hadoop-3.3.6-aarch64.tar.gz
        dest: /tmp/hadoop.tar.gz

    - name: Extract Hadoop
      unarchive:
        src: /tmp/hadoop.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Create Hadoop symlink
      file:
        src: /usr/local/hadoop-3.3.6
        dest: /usr/local/hadoop
        state: link

    - name: Set Hadoop environment variables
      lineinfile:
        path: /etc/profile.d/hadoop.sh
        line: "{{ item }}"
        create: yes
      loop:
        - 'export HADOOP_HOME=/usr/local/hadoop'
        - 'export PATH=$PATH:$HADOOP_HOME/bin'
        - 'export PATH=$PATH:$HADOOP_HOME/sbin'

    - name: Create Hadoop directories
      file:
        path: "{{ item }}"
        state: directory
        owner: hadoop
        group: hadoop
        mode: '0755'
      loop:
        - /usr/local/hadoop/tmp
        - /usr/local/hadoop/logs
        - /usr/local/hadoop/data
        - /usr/local/hadoop/name
        - /usr/local/hadoop/data/datanode
