---
- name: Install kURL and Configure Kubernetes
  hosts: all
  become: true
  tasks:

    # ✅ Vérifier la connexion Internet
    - name: Vérifier la connectivité réseau
      shell: ping -c 4 8.8.8.8
      register: ping_test
      ignore_errors: true

    - name: Afficher les résultats du test réseau
      debug:
        var: ping_test.stdout_lines

    # ✅ Installation des dépendances requises
    - name: Installer les dépendances requises
      apt:
        name:
          - curl
          - tar
          - ca-certificates
        state: present
        update_cache: yes

    # ✅ Lancer l'installation de kURL en arrière-plan
    - name: Lancer l'installation de kURL
      shell: curl -fsSL https://kurl.sh/726730f | sudo bash
      args:
        executable: /bin/bash
      async: 10800  # Timeout de 3 heures
      poll: 0
      register: kurl_async

    # ✅ Attendre la fin de l'installation de kURL
    - name: Attendre la fin de l'installation de kURL
      async_status:
        jid: "{{ kurl_async.ansible_job_id }}"
      register: kurl_status
      until: kurl_status.finished
      retries: 360  # Vérifier pendant 3 heures (360 x 30s)
      delay: 30

    # ✅ Afficher les logs de l'installation kURL
    - name: Afficher la sortie de l'installation de kURL
      debug:
        var: kurl_status.stdout_lines

    - name: Afficher les erreurs de l'installation de kURL
      debug:
        var: kurl_status.stderr_lines
