---
- name: Configure Kubernetes access
  hosts: all
  become: true
  tasks:
    # Basic system setup
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy
    # Configuration du répertoire .kube
    - name: Create .kube directory
      file:
        path: ~/.kube
        state: directory
        mode: '0755'

    # Copie du fichier de configuration
    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      ignore_errors: yes

    # Fix des permissions
    - name: Fix ownership of kube config
      file:
        path: ~/.kube/config
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    # Redémarrage des services Kubernetes
    - name: Restart kubelet service
      systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes

    # Vérification de la connexion
    - name: Test kubectl connection
      command: kubectl get nodes
      register: kubectl_test
      ignore_errors: yes

    - name: Display kubectl test result
      debug:
        var: kubectl_test.stdout_lines
