---
- name: Install Jenkins on Ubuntu and RHEL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"

  tasks:
    # Common proxy environment configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ubuntu-specific tasks
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Install Java (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Download Jenkins key (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Add Jenkins repository (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Install Jenkins (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: jenkins
        state: present
      register: jenkins_install_ubuntu

    # RHEL-specific tasks
    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == "RedHat"
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Install wget and Java dependencies (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name: 
          - wget
          - java-17-openjdk
          - fontconfig
        state: present

    - name: Download Jenkins repo (RHEL)
      when: ansible_os_family == "RedHat"
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Import Jenkins key (RHEL)
      when: ansible_os_family == "RedHat"
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Install Jenkins (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name: jenkins
        state: present
      register: jenkins_install_rhel

    # Common tasks for both distributions
    - name: Start and enable Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
      when: jenkins_install_ubuntu is success or jenkins_install_rhel is success

    - name: Wait for Jenkins to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 300

    - name: Get initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false
      when: jenkins_install_ubuntu is success or jenkins_install_rhel is success

    - name: Display Jenkins initial admin password
      debug:
        var: jenkins_password.stdout
      when: jenkins_install_ubuntu is success or jenkins_install_rhel is success

    - name: Print installation complete message
      debug:
        msg: "Jenkins has been installed successfully. Access it at https://{{ morpheus['server']['internalIp'] }}:8080"
