---
- name: Install Kong API Gateway
  hosts: all
  become: true
  vars:
    kong_version: "3.8.0.0"
  tasks:
    # DNS configuration for both Ubuntu and RHEL
    - name: Configure resolv.conf with Google DNS (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Configure resolv.conf with Google DNS (RHEL)
      when: ansible_os_family == "RedHat"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    # Clear proxy settings
    - name: Clear apt proxy settings (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy
    
    - name: Clear yum proxy settings (RHEL)
      when: ansible_os_family == "RedHat"
      shell: echo > /etc/yum.conf.d/90curtin-aptproxy
    
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
        
    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
        state: present
        
    - name: Download Kong deb package
      get_url:
        url: "https://packages.konghq.com/public/gateway-38/deb/debian/pool/bullseye/main/k/ko/kong-enterprise-edition_{{ kong_version }}/kong-enterprise-edition_{{ kong_version }}_$(dpkg --print-architecture).deb"
        dest: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
        
    - name: Install Kong package
      apt:
        deb: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
        state: present
        
    - name: Clean up downloaded deb file
      file:
        path: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
        state: absent
        
    - name: Print Kong installation complete message
      debug:
        msg: "Kong API Gateway has been installed successfully. Please configure it according to your needs."
    - name: Verify Kong installation
      command: kong version
      register: kong_version_output
      changed_when: false
    - name: Display Kong version
      debug:
        var: kong_version_output.stdout_lines
