---
- name: Install Kong API Gateway
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    kong_version: "3.8.0.0"
  connection: paramiko

  tasks:
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - curl
          - ca-certificates
        state: present

    - name: Download Kong deb package
      get_url:
        url: "https://packages.konghq.com/public/gateway-38/deb/debian/pool/bullseye/main/k/ko/kong-enterprise-edition_{{ kong_version }}/kong-enterprise-edition_{{ kong_version }}_$(dpkg --print-architecture).deb"
        dest: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Install Kong package
      apt:
        deb: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
        state: present

    - name: Clean up downloaded deb file
      file:
        path: "/tmp/kong-enterprise-edition-{{ kong_version }}.deb"
        state: absent

    - name: Print Kong installation complete message
      debug:
        msg: "Kong API Gateway has been installed successfully. Please configure it according to your needs."

    - name: Verify Kong installation
      command: kong version
      register: kong_version_output
      changed_when: false

    - name: Display Kong version
      debug:
        var: kong_version_output.stdout_lines
