- name: Configure kURL and Install Kubernetes
  hosts: all
  become: yes

  tasks:
    - name: Remove /etc/resolv.conf if it exists
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create /etc/resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    - name: Verify /etc/resolv.conf content
      command: cat /etc/resolv.conf
      register: resolv_check

    - name: Debug resolv.conf verification
      debug:
        msg: "Contents of /etc/resolv.conf: {{ resolv_check.stdout }}"

    - name: Disable and stop systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Run the Kurl installation script with auto-confirmation
      command: "yes | curl -fsSL https://kurl.sh/8eb26e2 | sudo bash"

    - name: Verify Kurl installation success
      command: kubectl version --client
      register: kubectl_version
      ignore_errors: yes

    - name: Debug kubectl version check
      debug:
        msg: "kubectl version output: {{ kubectl_version.stdout }}"
