---
- name: Install kURL using custom YAML configuration
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"  # Update with your proxy if required
    kurl_yaml_path: "/tmp/kurl-installer.yaml"
    kurl_url: "https://kurl.sh/<unique_id>"  # Replace <unique_id> with your generated kURL link
    kurl_installer_path: "/tmp/kurl-installer.sh"

  tasks:
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Reload environment variables
      shell: source /etc/environment
      register: env_reload
      ignore_errors: true

    - name: Upload kURL YAML configuration
      copy:
        src: "kurl-installer.yaml"  # Ensure this file is in your Ansible working directory
        dest: "{{ kurl_yaml_path }}"

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download the kURL installer script
      get_url:
        url: "{{ kurl_url }}"
        dest: "{{ kurl_installer_path }}"
        mode: '0755'
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Verify kURL installer script content
      shell: "cat {{ kurl_installer_path }}"
      register: script_content

    - name: Debug kURL installer script content
      debug:
        var: script_content.stdout

    - name: Run the kURL installer script
      shell: "{{ kurl_installer_path }}"
      args:
        creates: "/etc/kubernetes/admin.conf"  # Ensure idempotency
