- name: Install kURL on Ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    timeout: 7200

  tasks:
    - name: Fix dpkg if interrupted
      shell: |
        dpkg --configure -a
      ignore_errors: yes

    - name: Update apt cache
      shell: |
        rm -rf /var/lib/apt/lists/*
        apt-get clean
        DEBIAN_FRONTEND=noninteractive apt-get update
      args:
        executable: /bin/bash
      async: 300
      poll: 5

    - name: Install minimal required packages
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        name: curl
        state: present
        update_cache: no
      async: 300
      poll: 5

    - name: Download kURL installation script
      get_url:
        url: https://kurl.sh/fcc1994
        dest: /tmp/install.sh
        mode: '0755'
      async: 300
      poll: 5

    - name: Execute kURL installation script non-interactively
      shell: |
        export DEBIAN_FRONTEND=noninteractive
        yes | bash /tmp/install.sh
      args:
        executable: /bin/bash
      environment:
        DEBIAN_FRONTEND: noninteractive
      register: kurl_install
      async: "{{ timeout }}"
      poll: 30

    - name: Display installation output
      debug:
        var: kurl_install

    - name: Clean up
      file:
        path: /tmp/install.sh
        state: absent
