---
- name: Install kURL on Ubuntu
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    kurl_url: "https://kurl.sh/d6c2d72"  # Replace with your specific kURL installer link
    kurl_installer_path: "/tmp/kurl-installer.sh"

  tasks:
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Reload environment variables
      shell: source /etc/environment
      register: env_reload
      ignore_errors: true

    - name: Ensure curl is installed
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download the kURL installer script
      get_url:
        url: "{{ kurl_url }}"
        dest: "{{ kurl_installer_path }}"
        mode: '0755'

    - name: Run the kURL installer script
      shell: "{{ kurl_installer_path }}"
      args:
        creates: "/etc/kubernetes/admin.conf"  # Ensure idempotency
