- name: Configure kURL and Install Kubernetes
  hosts: all
  become: yes
  vars:
    ansible_become_password: "ACSCloud!2021!"

  tasks:
    - name: Remove /etc/resolv.conf if it exists
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Create /etc/resolv.conf with Google DNS
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    - name: Disable and stop systemd-resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Run the Kurl installation script
      shell: |
        yes | curl -fsSL https://kurl.sh/8eb26e2 | sudo bash
      args:
        executable: /bin/bash
      register: kurl_install

    - name: Debug Kurl installation output
      debug:
        msg: "{{ kurl_install.stdout }}"
