---
- name: Install kURL on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Ensure system is Ubuntu
      fail:
        msg: "This playbook is only for Ubuntu systems"
      when: ansible_distribution != "Ubuntu"

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name: 
          - curl
          - sudo
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - python3-setuptools
        state: present

    - name: Create temporary directory for kURL
      file:
        path: /tmp/kurl-install
        state: directory
        mode: '0755'

    - name: Download kURL installation script
      get_url:
        url: https://kurl.sh/fcc1994
        dest: /tmp/kurl-install/install.sh
        mode: '0755'

    - name: Execute kURL installation script
      shell: |
        cd /tmp/kurl-install
        bash install.sh
      args:
        executable: /bin/bash
      register: kurl_install
      ignore_errors: yes

    - name: Display installation output
      debug:
        var: kurl_install.stdout_lines
      when: kurl_install.stdout_lines is defined

    - name: Display errors if installation failed
      debug:
        msg: "Installation failed with error: {{ kurl_install.stderr_lines }}"
      when: kurl_install.failed

    - name: Clean up installation files
      file:
        path: /tmp/kurl-install
        state: absent
