- name: Install kURL on Ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    timeout: 7200
    dns_servers:
      - "8.8.8.8"
      - "8.8.4.4"

  tasks:
    - name: Backup resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.backup
        remote_src: yes

    - name: Configure DNS resolvers
      template:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4

    - name: Disable swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^/#/' /etc/fstab

    - name: Install minimal required packages
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        name: curl
        state: present
        update_cache: yes
      async: 300
      poll: 5

    - name: Install kURL
      shell: |
        echo "y" | curl -fsSL https://kurl.sh/fcc1994 | bash
      args:
        executable: /bin/bash
      register: kurl_install
      async: "{{ timeout }}"
      poll: 30

    - name: Display installation output
      debug:
        var: kurl_install
