---
- name: Install kURL on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Fix dpkg if interrupted
      shell: |
        dpkg --configure -a
      ignore_errors: yes

    - name: Update apt cache
      shell: |
        rm -rf /var/lib/apt/lists/*
        apt-get clean
        apt-get update
      args:
        executable: /bin/bash
      ignore_errors: yes

    - name: Install minimal required packages
      apt:
        name: curl
        state: present
        update_cache: no
      ignore_errors: yes

    - name: Download kURL installation script
      get_url:
        url: https://kurl.sh/fcc1994
        dest: /tmp/install.sh
        mode: '0755'

    - name: Execute kURL installation script
      shell: |
        bash /tmp/install.sh
      args:
        executable: /bin/bash
      register: kurl_install
      ignore_errors: yes

    - name: Display installation output
      debug:
        var: kurl_install.stdout_lines
      when: kurl_install.stdout_lines is defined

    - name: Clean up
      file:
        path: /tmp/install.sh
        state: absent
