---
- name: Installer kURL sur Ubuntu
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Mettre à jour les paquets du système
      apt:
        update_cache: yes
        upgrade: yes

    - name: Configurer le proxy pour apt
      copy:
        content: |
          Acquire::http::Proxy "http://10.1.38.12:3128";
          Acquire::https::Proxy "http://10.1.38.12:3128";
        dest: /etc/apt/apt.conf.d/95proxies
        mode: '0644'

    - name: Configurer le proxy pour l'environnement
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        create: yes
      with_items:
        - 'http_proxy=http://10.1.38.12:3128'
        - 'https_proxy=http://10.1.38.12:3128'
        - 'HTTP_PROXY=http://10.1.38.12:3128'
        - 'HTTPS_PROXY=http://10.1.38.12:3128'

    - name: Installer curl et wget
      apt:
        name:
          - curl
          - wget
        state: present

    - name: Télécharger et exécuter le script d'installation kURL
      shell: |
        echo "{{ sudo_password }}" | sudo -S bash -c "curl -sSL {{ kurl_url }} | bash"
      args:
        executable: /bin/bash
      register: install_result
      ignore_errors: yes

    - name: Vérifier le résultat de l'installation
      debug:
        var: install_result.stdout
