---
- name: Installer kURL sur Ubuntu 22
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"

  tasks:
    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installer curl
      apt:
        name: curl
        state: present

    - name: Télécharger et installer kURL
      shell: |
        curl -sSL {{ kurl_url }} | sudo bash
      args:
        chdir: /tmp
        creates: /usr/local/bin/kurl

    - name: Vérifier si kURL est installé
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Afficher la version de kURL
      debug:
        var: kurl_version.stdout
