- name: Install kURL on Ubuntu
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    timeout: 7200

  tasks:
    - name: Install expect
      apt:
        name: expect
        state: present
        update_cache: yes
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Create expect script
      copy:
        dest: /tmp/kurl_install.exp
        mode: '0755'
        content: |
          #!/usr/bin/expect -f
          set timeout -1
          spawn bash /tmp/install.sh
          expect {
            "*(y/N)*" { send "y\r"; exp_continue }
            "*(Y/n)*" { send "y\r"; exp_continue }
            "*(y/n)*" { send "y\r"; exp_continue }
            eof
          }

    - name: Download kURL installation script
      get_url:
        url: https://kurl.sh/fcc1994
        dest: /tmp/install.sh
        mode: '0755'

    - name: Execute kURL installation with expect
      shell: |
        /usr/bin/expect /tmp/kurl_install.exp
      args:
        executable: /bin/bash
      register: kurl_install
      async: "{{ timeout }}"
      poll: 30

    - name: Display installation output
      debug:
        var: kurl_install

    - name: Clean up
      file:
        path: 
          - /tmp/install.sh
          - /tmp/kurl_install.exp
        state: absent
