- name: Installer Java pour Hadoop sur Ubuntu/Debian
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour les paquets
      apt:
        update_cache: yes

    - name: Installer OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
