---
- name: Installer kURL sur Ubuntu avec gestion interactive
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Installer curl et wget
      apt:
        name:
          - curl
          - wget
        state: present

    - name: Télécharger le script d'installation kURL
      shell: |
        curl -sSL {{ kurl_url }} -o /tmp/kurl_install.sh
      args:
        executable: /bin/bash

    - name: Exécuter le script d'installation kURL avec gestion interactive
      expect:
        command: bash /tmp/kurl_install.sh
        responses:
          'Would you like to continue? [Y/n]': 'y'  # Automatiser la réponse 'y' pour continuer
          'Enter your password': "{{ sudo_password }}"  # Automatiser la saisie du mot de passe
      register: install_result
      ignore_errors: yes

    - name: Vérifier le résultat de l'installation
      debug:
        var: install_result.stdout
