- name: Installer Java pour Hadoop sur Ubuntu 22.04
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Installer OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
        force_apt_get: yes
