---
- name: Configure Kubernetes Master Node using kURL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"  # Optional proxy, remove if not needed
    kurl_url: "https://kurl.sh/d6c2d72" # Your kURL link

  tasks:
    - name: Configure HTTP proxy for APT (Optional)
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies
      when: proxy_url is defined

    - name: Configure proxy for the environment (Optional)
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'
      when: proxy_url is defined

    - name: Install curl if not already installed
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download and run kURL installer for Kubernetes
      ansible.builtin.shell: |
        curl -sSL {{ kurl_url }} | sudo bash
      args:
        warn: false

    - name: Wait for the kURL installer to complete
      wait_for:
        path: /var/lib/rancher/k3s/k3s.yaml
        state: present
        timeout: 1200

    - name: Print success message
      debug:
        msg: "Kubernetes master node installation completed successfully using kURL."
