---
- name: Configure kURL with Proxy and Install on Ubuntu
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"  # Your proxy URL
    kurl_url: "https://k8s.kurl.sh/bundle/latest.tar.gz"  # kURL URL for bundle

  tasks:
    # Configure HTTP proxy for APT
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    # Configure HTTP proxy for the environment
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ensure system is updated
    - name: Ensure system is updated
      apt:
        update_cache: yes
        upgrade: dist

    # Install curl if it's not installed
    - name: Install required dependencies (curl)
      apt:
        name: curl
        state: present

    # Download the kURL bundle
    - name: Download kURL bundle
      get_url:
        url: "{{ kurl_url }}"
        dest: "/tmp/latest.tar.gz"

    # Extract the downloaded tarball
    - name: Extract the kURL bundle
      unarchive:
        src: "/tmp/latest.tar.gz"
        dest: "/tmp/kurl_bundle"
        remote_src: yes

    # Run the kURL installation script
    - name: Run the kURL installer script
      shell: "sudo /tmp/kurl_bundle/install.sh"
      args:
        creates: "/usr/local/bin/kurl"  # Ensures it only runs once if kURL is installed

    # Verify kURL installation
    - name: Verify kURL installation
      command: "kurl version"
      register: kurl_version
      ignore_errors: true

    - debug:
        var: kurl_version.stdout
