---
- name: Install and Configure MongoDB
  hosts: all
  become: true
  gather_facts: true
  vars:
    mongodb_version: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['version'] | default('6.0') }}"  
    mongodb_repo_url: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
    proxy_url: "http://10.1.38.2:3128"
    db_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"
    db_vars_provided: false
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    - name: Ensure Ansible remote tmp directory exists and is writable
      file:
        path: "{{ ansible_remote_tmp }}"
        state: directory
        mode: '1777'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become: true

    - name: Check if database variables are provided
      set_fact:
        db_vars_provided: true
      when: 
        - db_password != ''
        - db_user != ''
        - db_name != ''

    - name: Configure HTTP proxy for yum (RHEL)
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes
      when: ansible_os_family == 'RedHat'

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Register and subscribe RHEL system
      when: ansible_os_family == 'RedHat'
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == 'RedHat'
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Add MongoDB GPG key
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt_key:
        url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
        state: present

    - name: Add MongoDB repository (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
        state: present

    - name: Update apt cache
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        update_cache: yes

    - name: Add MongoDB repository (RedHat)
      when: ansible_distribution == 'RedHat'
      yum_repository:
        name: "mongodb-org-{{ mongodb_version }}"
        description: "MongoDB Repository"
        baseurl: "{{ mongodb_repo_url }}"
        gpgcheck: yes
        enabled: yes
        gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"

    - name: Update YUM cache
      when: ansible_distribution == 'RedHat'
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install MongoDB
      when: ansible_distribution == 'RedHat'
      yum:
        name: 
          - mongodb-org
          - mongodb-mongosh
        state: present

    - name: Install MongoDB on Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - mongodb-org
          - mongodb-mongosh
        state: present

    - name: Enable and start MongoDB service
      systemd:
        name: mongod
        enabled: yes
        state: started

    - name: Set up MongoDB user and database via shell
      when: db_vars_provided
      shell: |
        mongosh {{ db_name }} --eval "db.createUser({user: '{{ db_user }}', pwd: '{{ db_password }}', roles: [{role: 'readWrite', db: '{{ db_name }}'}, {role: 'dbAdmin', db: '{{ db_name }}'}]})"
      args:
        chdir: /tmp
      register: mongo_user_setup
      changed_when: "'Successfully added user' in mongo_user_setup.stdout"
      failed_when: "'Error' in mongo_user_setup.stderr"

    - name: Print status of MongoDB setup
      debug:
        msg: "MongoDB setup completed with user {{ db_user }} and database {{ db_name }}"
      when: db_vars_provided
