---
- name: Install MySQL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
  connection: paramiko

  tasks:
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is started and enabled
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Get MySQL version
      command: mysql --version
      register: mysql_version
      changed_when: false

    - name: Display MySQL version
      debug:
        var: mysql_version.stdout

    - name: Print MySQL installation complete message
      debug:
        msg: "MySQL has been installed successfully. Remember to secure your installation by running: sudo mysql_secure_installation "
  
