---
- name: Define Nagios target machines
  hosts: all
  gather_facts: no
  tasks:
    - name: Add target machines dynamically
      add_host:
        name: "{{ item.ip }}"
        ansible_user: "{{ item.user }}"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        groups: nagios_servers
      loop:
        - { ip: "192.168.1.10", user: "ubuntu" }
        - { ip: "192.168.1.11", user: "ubuntu" }

- name: Install Nagios on target machines
  hosts: all
  become: yes
  vars:
    nagios_version: "4.4.6"
    plugins_version: "2.3.3"
    nagios_user: "nagios"
    nagios_group: "nagcmd"
    nagios_web_user: "nagiosadmin"
    nagios_password: "{{ lookup('env', 'NAGIOS_PASSWORD') | default('ACSCloud!2021!', true) }}"  # Mot de passe modifiable via variable d'environnement

  tasks:
    - name: Update system
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - php
          - php-gd
          - php-cli
          - unzip
          - wget
          - libgd-dev
          - libapache2-mod-php
          - build-essential
          - libperl-dev
          - libssl-dev
          - daemon
          - curl
        state: present

    - name: Create Nagios user and group
      user:
        name: "{{ nagios_user }}"
        comment: "Nagios Monitoring User"
        create_home: no
        shell: /bin/false

    - name: Create nagcmd group
      group:
        name: "{{ nagios_group }}"
        state: present

    - name: Add Nagios user to nagcmd group
      user:
        name: "{{ nagios_user }}"
        groups: "{{ nagios_group }}"
        append: yes

    - name: Add www-data to nagcmd group
      user:
        name: "www-data"
        groups: "{{ nagios_group }}"
        append: yes

    - name: Download Nagios Core
      get_url:
        url: "https://github.com/NagiosEnterprises/nagioscore/releases/download/nagios-{{ nagios_version }}/nagios-{{ nagios_version }}.tar.gz"
        dest: "/tmp/nagios.tar.gz"

    - name: Extract Nagios Core
      ansible.builtin.unarchive:
        src: "/tmp/nagios.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Compile and install Nagios Core
      shell: |
        cd /tmp/nagios-{{ nagios_version }}
        ./configure --with-nagios-group={{ nagios_user }} --with-command-group={{ nagios_group }}
        make all
        make install
        make install-init
        make install-commandmode
        make install-config

    - name: Download Nagios Plugins
      get_url:
        url: "https://nagios-plugins.org/download/nagios-plugins-{{ plugins_version }}.tar.gz"
        dest: "/tmp/nagios-plugins.tar.gz"

    - name: Extract Nagios Plugins
      ansible.builtin.unarchive:
        src: "/tmp/nagios-plugins.tar.gz"
        dest: "/tmp/"
        remote_src: yes

    - name: Compile and install Nagios Plugins
      shell: |
        cd /tmp/nagios-plugins-{{ plugins_version }}
        ./configure --with-nagios-user={{ nagios_user }} --with-nagios-group={{ nagios_group }}
        make
        make install

    - name: Install Nagios web configuration
      shell: |
        make install-webconf
        a2enmod rewrite cgi
        systemctl restart apache2
      args:
        chdir: "/tmp/nagios-{{ nagios_version }}"

    - name: Set up Nagios admin password
      shell: "htpasswd -bc /usr/local/nagios/etc/htpasswd.users {{ nagios_web_user }} {{ nagios_password }}"

    - name: Start and enable Nagios
      systemd:
        name: nagios
        state: started
        enabled: yes

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
