---
- name: Installation de Redis sur Ubuntu
  hosts: all
  become: yes
  tasks:
    # Basic system setup
    - name: Configure resolv.conf with Google DNS
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Clear apt proxy settings
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy
      
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    
    # Redis installation
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
  
  - name: Install Redis
    apt:
      name: redis-server
      state: present
  
  - name: Start Redis
    service:
      name: redis-server
      state: started
      enabled: yes
