- hosts: all
  become: yes
  tasks:
    - name: To install NetData dependencies
      apt:
        name:
          - git
          - zlib1g-dev
          - uuid-dev
          - libmnl-dev
          - pkg-config
          - curl
          - gcc
          - make
          - autoconf
          - autoconf-archive
          - autogen
          - automake
          - python3-mysqldb
          - lm-sensors
          - python3-psycopg2
          - netcat
          - nodejs
          - libuv1-dev
        update_cache: yes
        state: present

    - name: Clone NetData repository
      git:
        repo: 'https://github.com/firehol/netdata.git'
        dest: /opt/netdata/
        clone: yes
        update: yes

    - name: Run the NetData installer script
      shell: bash netdata-installer.sh --dont-wait --libs-are-really-here
      args:
        chdir: /opt/netdata

  handlers:
    - name: Restart NetData service
      service:
        name: netdata
        state: restarted
