---
- name: Install and Configure Zabbix 7.0
  hosts: all
  become: true
  become_method: sudo
  become_pass: "{{ lookup('cypher','secret/pw') }}"
  vars:
    proxy_url: "http://10.1.38.2:3128"
    mysql_root_password: "Password123@"
    zabbix_db_password: "Password123@"

  tasks:
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'
    - name: Install wget
      apt:
        name: wget
        state: present
        update_cache: yes

    - name: Download Zabbix repository package
      shell: wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb

    - name: Install Zabbix repository
      apt:
        deb: zabbix-release_latest+ubuntu22.04_all.deb
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix packages
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - mysql-server
        state: present

    - name: Wait for MySQL to start
      wait_for:
        port: 3306
        timeout: 30

    - name: Create Zabbix database and set privileges
      shell: |
        mysql -uroot <<EOF
        create database zabbix character set utf8mb4 collate utf8mb4_bin;
        create user zabbix@localhost identified by '{{ zabbix_db_password }}';
        grant all privileges on zabbix.* to zabbix@localhost;
        set global log_bin_trust_function_creators = 1;
        quit;
        EOF

    - name: Import Zabbix schema
      shell: zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -uzabbix -p{{ zabbix_db_password }} zabbix

    - name: Disable log_bin_trust_function_creators
      shell: |
        mysql -uroot <<EOF
        set global log_bin_trust_function_creators = 0;
        quit;
        EOF

    - name: Configure Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: "DBPassword={{ zabbix_db_password }}"

    - name: Start and enable Zabbix services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - zabbix-server
        - zabbix-agent
        - apache2

    - name: Clean up downloaded package
      file:
        path: zabbix-release_latest+ubuntu22.04_all.deb
        state: absent

    - name: Print installation complete message
      debug:
        msg: "Zabbix has been installed successfully. Access the web interface at http://{{ ansible_default_ipv4.address }}/zabbix"
