---
- name: Install Prometheus
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    prometheus_version: "2.55.1"
    prometheus_dir: "/opt/prometheus"
    prometheus_user: "prometheus"
    prometheus_group: "prometheus"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    # Ubuntu-specific tasks
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - wget
          - tar
        state: present

    # RHEL-specific tasks
    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == 'RedHat'
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Register and subscribe RHEL system
      when: ansible_os_family == 'RedHat'
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Enable required RHEL repositories
      when: ansible_os_family == 'RedHat'
      command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Install required packages (RHEL)
      when: ansible_os_family == 'RedHat'
      shell: |
        yum install -y wget tar

    # Common tasks for both distributions
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Create Prometheus group
      group:
        name: "{{ prometheus_group }}"
        system: yes
        state: present

    - name: Create Prometheus user
      user:
        name: "{{ prometheus_user }}"
        system: yes
        shell: "/sbin/nologin"
        group: "{{ prometheus_group }}"
        createhome: no

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      loop:
        - "{{ prometheus_dir }}"
        - "{{ prometheus_dir }}/data"

    - name: Download Prometheus
      shell: |
        export http_proxy="{{ proxy_url }}"
        export https_proxy="{{ proxy_url }}"
        curl -x {{ proxy_url }} -L -k \
          "https://github.com/prometheus/prometheus/releases/download/v2.55.1/prometheus-2.55.1.linux-amd64.tar.gz" \
          -o "/tmp/prometheus-2.55.1.linux-amd64.tar.gz"
      args:
        creates: "/tmp/prometheus-2.55.1.linux-amd64.tar.gz"

    # Simple verification
    - name: Check if download was successful
      stat:
        path: "/tmp/prometheus-2.55.1.linux-amd64.tar.gz"
      register: prometheus_archive

    - name: Fail if download was not successful
      fail:
        msg: "Failed to download Prometheus archive"
      when: not prometheus_archive.stat.exists

    - name: Extract Prometheus archive
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "{{ prometheus_dir }}/{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
        remote_src: yes
      loop:
        - prometheus
        - promtool

    - name: Copy Prometheus configuration
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus.yml"
        dest: "{{ prometheus_dir }}/prometheus.yml"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
        remote_src: yes

    - name: Create Prometheus systemd service file
      template:
        src: prometheus.service.j2
        dest: /etc/systemd/system/prometheus.service
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Prometheus service is started and enabled
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Clean up downloaded files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

    - name: Print Prometheus installation complete message
      debug:
        msg: "Prometheus has been installed successfully. It should be accessible on https://{{ morpheus['server']['internalIp'] }}:9090"

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
