---
- name: Install Prometheus on Ubuntu and RHEL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    prometheus_version: "2.43.0"
    rhel_username: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelEmail'] | default('') }}"
    rhel_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelPw'] | default('') }}"
    prometheus_user: prometheus
    prometheus_group: prometheus
    prometheus_config_dir: /etc/prometheus
    prometheus_data_dir: /var/lib/prometheus

  tasks:  
    # Ubuntu-specific pre-tasks
    - name: Configure APT to use proxy
      when: ansible_distribution == "Ubuntu"
      copy:
        dest: /etc/apt/apt.conf.d/95proxy
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: |
        export http_proxy={{ proxy_url }}
        export https_proxy={{ proxy_url }}
        apt-get update
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # RHEL-specific tasks
    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == "RedHat"
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Enable required RHEL repositories
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
      register: repo_result
      failed_when: repo_result.rc != 0 and 'already enabled' not in repo_result.stderr
      changed_when: repo_result.rc == 0

    - name: Enable BaseOS repository (RHEL)
      when: ansible_os_family == "RedHat"
      command: subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
      register: baseos_result
      failed_when: baseos_result.rc != 0 and 'already enabled' not in baseos_result.stderr
      changed_when: baseos_result.rc == 0

    - name: Create dnf proxy configuration
      when: ansible_os_family == "RedHat"
      copy:
        dest: /etc/dnf/dnf.conf
        content: |
          [main]
          gpgcheck=1
          installonly_limit=3
          clean_requirements_on_remove=True
          best=True
          proxy={{ proxy_url }}
        mode: '0644'

    - name: Clean dnf cache
      when: ansible_os_family == "RedHat"
      command: dnf clean all

    - name: Install wget (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name: wget
        state: present
        update_cache: yes

    - name: Install wget (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: wget
        state: present
  
    # Common tasks
    - name: Create Prometheus system group
      group:
        name: "{{ prometheus_group }}"
        system: yes
        state: present

    - name: Create Prometheus system user
      user:
        name: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        system: yes
        shell: /sbin/nologin
        create_home: no
  

    - name: Install required packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: 
          - tar
          - gzip
          - bzip2
          - xz-utils
          - unzip
          - ca-certificates
        state: present
        update_cache: yes

    # Clean existing file if it exists
    - name: Remove existing Prometheus archive if exists
      file:
        path: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        state: absent

    # Download for Ubuntu
    - name: Download Prometheus (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: |
        curl -x {{ proxy_url }} -L \
        --insecure \
        --max-time 300 \
        --retry 3 \
        --retry-delay 5 \
        --retry-max-time 900 \
        -H "Accept: application/octet-stream" \
        -H "Cache-Control: no-cache" \
        https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz \
        -o /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
      args:
        creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"
  
    - name: Download Prometheus (RHEL)
      when: ansible_os_family == "RedHat"
      shell: |
        wget --no-check-certificate --quiet \
        --proxy=on \
        --proxy-user= \
        --proxy-password= \
        -e http_proxy={{ proxy_url }} \
        -e https_proxy={{ proxy_url }} \
        https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz \
        -O /tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz
      args:
        creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"

    - name: Extract Prometheus archive
      unarchive:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Create Prometheus directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      with_items:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Copy Prometheus binaries
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        remote_src: yes
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0755'
      with_items:
        - prometheus
        - promtool

    - name: Copy Prometheus configuration files
      copy:
        src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
        dest: "{{ prometheus_config_dir }}/{{ item }}/"
        remote_src: yes
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
      with_items:
        - console_libraries
        - consoles

    - name: Create Prometheus configuration
      copy:
        dest: "{{ prometheus_config_dir }}/prometheus.yml"
        content: |
          global:
            scrape_interval: 15s
            evaluation_interval: 15s

          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']

            - job_name: 'node'
              static_configs:
                - targets: ['localhost:9100']
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        mode: '0644'
      notify: restart prometheus

    - name: Create Prometheus systemd service
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ prometheus_user }}
          Group={{ prometheus_group }}
          Type=simple
          ExecStart=/usr/local/bin/prometheus \
              --config.file {{ prometheus_config_dir }}/prometheus.yml \
              --storage.tsdb.path {{ prometheus_data_dir }}/ \
              --web.console.templates={{ prometheus_config_dir }}/consoles \
              --web.console.libraries={{ prometheus_config_dir }}/console_libraries

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      notify: restart prometheus

    - name: Set directory ownership
      file:
        path: "{{ item }}"
        owner: "{{ prometheus_user }}"
        group: "{{ prometheus_group }}"
        recurse: yes
      with_items:
        - "{{ prometheus_config_dir }}"
        - "{{ prometheus_data_dir }}"

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Wait for Prometheus to start
      wait_for:
        port: 9090
        timeout: 60

    - name: Clean up downloaded files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
        - "/tmp/prometheus-{{ prometheus_version }}.linux-amd64"

  handlers:
    - name: restart prometheus
      systemd:
        name: prometheus
        state: restarted

    - name: Print Prometheus installation complete message
      debug:
        msg: "Prometheus has been installed successfully. It should be accessible on https://{{ morpheus['server']['internalIp'] }}:9090"
