---

- name: install Rclone and start web gui
  hosts: unassigned
  become: true
  tasks:

    - name: apdate apt
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: install Rclone using apt
      apt:
        name: rclone
        state: present

