---
- name: Install and Configure SQL Server
  hosts: all
  become: true
  gather_facts: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    sql_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomPassword'] | default('SqlServer2019!') }}"
    db_user: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomUser'] | default('') }}"
    db_name: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['dbCustomName'] | default('') }}"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"
    sql_server_edition: "Developer"

  tasks:
    # Common proxy configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Download and add the Microsoft GPG key
      shell: |
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
      args:
        creates: /usr/share/keyrings/microsoft-prod.gpg

    - name: Add the Microsoft SQL Server repository
      shell: |
        curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/mssql-server-2022.list | tee /etc/apt/sources.list.d/mssql-server-2022.list
      args:
        creates: /etc/apt/sources.list.d/mssql-server-2022.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Microsoft SQL Server
      apt:
        name: mssql-server
        state: present

    - name: Configure MSSQL with password and edition
      shell: |
        /opt/mssql/bin/mssql-conf setup --accept-eula \
        --set-sa-password "{{ sql_password }}" \
        --edition {{ sql_server_edition }}
      environment:
        MSSQL_SA_PASSWORD: "{{ sql_password }}"
      register: mssql_setup
      changed_when: mssql_setup.rc == 0
      failed_when: mssql_setup.rc != 0

    - name: Ensure MSSQL service is running
      systemd:
        name: mssql-server
        state: started
        enabled: yes
