---
- name: Install and Configure Squid Proxy
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    squid_port: 3128
    allowed_networks:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
    squid_config: |
      # Basic Squid configuration
      http_port {{ squid_port }}

      # Access control
      acl localnet src {{ allowed_networks | join(' ') }}
      acl SSL_ports port 443
      acl Safe_ports port 80          # http
      acl Safe_ports port 21          # ftp
      acl Safe_ports port 443         # https
      acl Safe_ports port 70          # gopher
      acl Safe_ports port 210         # wais
      acl Safe_ports port 1025-65535  # unregistered ports
      acl Safe_ports port 280         # http-mgmt
      acl Safe_ports port 488         # gss-http
      acl Safe_ports port 591         # filemaker
      acl Safe_ports port 777         # multiling http
      acl CONNECT method CONNECT

      # Only allow cachemgr access from localhost
      http_access allow localhost manager
      http_access deny manager

      # Deny requests to certain unsafe ports
      http_access deny !Safe_ports

      # Deny CONNECT to other than secure SSL ports
      http_access deny CONNECT !SSL_ports

      # Allow localhost and localnet
      http_access allow localhost
      http_access allow localnet

      # And finally deny all other access to this proxy
      http_access deny all

      # Leave coredumps in the first cache dir
      coredump_dir /var/spool/squid

      # Add any of your own refresh_pattern entries above these.
      refresh_pattern ^ftp:           1440    20%     10080
      refresh_pattern ^gopher:        1440    0%      1440
      refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
      refresh_pattern .               0       20%     4320

  tasks:
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Squid
      apt:
        name: squid
        state: present

    - name: Create Squid configuration file
      copy:
        content: "{{ squid_config }}"
        dest: /etc/squid/squid.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart Squid

    - name: Ensure Squid service is started and enabled
      systemd:
        name: squid
        state: started
        enabled: yes

    - name: Open firewall port for Squid
      ufw:
        rule: allow
        port: "{{ squid_port }}"
        proto: tcp

    - name: Get Squid version
      command: squid -v
      register: squid_version
      changed_when: false

    - name: Display Squid version
      debug:
        var: squid_version.stdout_lines

    - name: Print Squid installation complete message
      debug:
        msg: "Squid proxy has been installed successfully and is listening on port {{ squid_port }}."

  handlers:
    - name: Restart Squid
      systemd:
        name: squid
        state: restarted
