---
- name: Test Cypher Detection
  hosts: all
  become: true
  vars:
    sudo_password: "{{ lookup('cypher', 'secret=pw') }}"

  tasks:
    - name: Display Cypher-read value
      debug:
        msg: "Cypher read value for sudo_password: {{ sudo_password }}"
