---
- name: Install Light Desktop Environment
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"

  tasks:
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Kill debconf-communicate processes
      shell: pkill -9 debconf-communicate || true
      ignore_errors: yes

    - name: Remove all lock files and temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/dpkg/lock-frontend
        - /var/lib/dpkg/lock
        - /var/cache/debconf/config.dat.lock
        - /var/cache/debconf/config.dat
        - /var/cache/debconf/config.dat-old
        - /var/lib/apt/lists/lock
        - /var/lib/apt/lists/partial
      ignore_errors: yes

    - name: Create new debconf database
      shell: |
        touch /var/cache/debconf/config.dat
      ignore_errors: yes
      
    - name: Reconfigure dpkg
      shell: dpkg --configure -a
      
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install XFCE Desktop
      apt:
        name: xfce4
        state: present

    - name: Reboot the system
      reboot:
        reboot_timeout: 600
