---
- name: Install WildFly
  hosts: all
  become: true
  gather_facts: true
  vars:
    proxy_url: "http://10.1.38.2:3128"
    wildfly_version: "34.0.0.Final"
    rhel_username: "mmajnioui@powerm.ma"
    rhel_password: "{{ lookup('cypher','secret=secret/rhelpw') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    # Common proxy configuration
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # Ubuntu-specific tasks
    - name: Configure HTTP proxy for apt (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install OpenJDK 17 (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name: openjdk-17-jdk
        state: present

    # RHEL-specific tasks
    - name: Configure HTTP proxy for yum (RHEL)
      when: ansible_os_family == 'RedHat'
      lineinfile:
        path: /etc/yum.conf
        line: 'proxy={{ proxy_url }}'
        create: yes

    - name: Register and subscribe RHEL system
      when: ansible_os_family == 'RedHat'
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Install OpenJDK 17 (RHEL)
      when: ansible_os_family == 'RedHat'
      dnf:
        name: java-17-openjdk-devel
        state: present

    # Common tasks for both distributions
    - name: Create WildFly group
      group:
        name: wildfly
        system: yes
        state: present

    - name: Create WildFly user
      user:
        name: wildfly
        group: wildfly
        system: yes
        shell: /sbin/nologin
        home: /opt/wildfly
        create_home: no

    - name: Download WildFly
      get_url:
        url: "https://github.com/wildfly/wildfly/releases/download/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.tar.gz"
        dest: "/tmp/wildfly-{{ wildfly_version }}.tar.gz"
      environment:
        http_proxy: "{{ proxy_url }}"
        https_proxy: "{{ proxy_url }}"

    - name: Create WildFly directory
      file:
        path: /opt/wildfly
        state: directory

    - name: Extract WildFly archive
      unarchive:
        src: "/tmp/wildfly-{{ wildfly_version }}.tar.gz"
        dest: /opt
        remote_src: yes
        creates: "/opt/wildfly-{{ wildfly_version }}"

    - name: Create symbolic link
      file:
        src: "/opt/wildfly-{{ wildfly_version }}"
        dest: /opt/wildfly
        state: link
        force: yes

    - name: Set WildFly ownership
      file:
        path: /opt/wildfly
        owner: wildfly
        group: wildfly
        recurse: yes

    - name: Create WildFly configuration directory
      file:
        path: /etc/wildfly
        state: directory

    - name: Copy WildFly configuration files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        remote_src: yes
      with_items:
        - { src: "/opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf", dest: "/etc/wildfly/" }
        - { src: "/opt/wildfly/docs/contrib/scripts/systemd/wildfly.service", dest: "/etc/systemd/system/" }
        - { src: "/opt/wildfly/docs/contrib/scripts/systemd/launch.sh", dest: "/opt/wildfly/bin/" }

    - name: Make scripts executable
      file:
        path: /opt/wildfly/bin
        mode: '0755'
        recurse: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Start and enable WildFly service
      systemd:
        name: wildfly
        state: started
        enabled: yes

    - name: Clean up downloaded files
      file:
        path: "/tmp/wildfly-{{ wildfly_version }}.tar.gz"
        state: absent
      ignore_errors: yes

    - name: Wait for WildFly to start
      wait_for:
        port: 8080
        delay: 10
        timeout: 60

    - name: Display WildFly installation complete message
      debug:
        msg: "WildFly has been installed successfully. Access it at http://localhost:8080"
