---
- hosts: all
  become: yes
  tasks:
    # Step 1: Configure DNS nameservers
    - name: Configure DNS nameservers
      blockinfile:
        path: /etc/resolv.conf
        block: |
          nameserver 8.8.8.8
          nameserver 8.8.4.4
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DNS"

    # Step 2: Update apt cache and install required packages
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ssh
        - rsync

    # Step 3: Install Java (OpenJDK 8)
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    # Step 4: Download Hadoop
    - name: Download Hadoop
      get_url:
        url: https://dlcdn.apache.org/hadoop/common/hadoop-3.4.1/hadoop-3.4.1-src.tar.gz
        dest: /tmp/hadoop-3.4.1-src.tar.gz
        timeout: 60
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 10

    # Step 5: Extract Hadoop
    - name: Extract Hadoop
      unarchive:
        src: /tmp/hadoop-3.4.1-src.tar.gz
        dest: /opt/
        remote_src: yes

    # Step 6: Create Hadoop directory
    - name: Create Hadoop directory
      file:
        path: /opt/hadoop
        state: link
        src: /opt/hadoop-3.4.1-src

    # Step 7.1: Define Hadoop environment variables template
    - name: Set Hadoop environment variables template
      set_fact:
        hadoop_env_sh: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export HADOOP_HOME=/opt/hadoop
          export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
          export HADOOP_LOG_DIR=/opt/hadoop/logs
          export HADOOP_PID_DIR=/opt/hadoop/pids

    # Step 7: Set Hadoop environment variables
    - name: Set Hadoop environment variables
      copy:
        content: "{{ hadoop_env_sh }}"
        dest: /opt/hadoop/etc/hadoop/hadoop-env.sh

    # Step 8.1: Define core-site.xml template
    - name: Set core-site.xml template
      set_fact:
        core_site_xml: |
          <configuration>
              <property>
                  <name>fs.defaultFS</name>
                  <value>hdfs://{{ ansible_facts['hostname'] }}:9000</value>
              </property>
          </configuration>

    # Step 8: Configure core-site.xml
    - name: Configure core-site.xml
      copy:
        content: "{{ core_site_xml }}"
        dest: /opt/hadoop/etc/hadoop/core-site.xml

    # Step 9.1: Define hdfs-site.xml template
    - name: Set hdfs-site.xml template
      set_fact:
        hdfs_site_xml: |
          <configuration>
              <property>
                  <name>dfs.replication</name>
                  <value>3</value>
              </property>
              <property>
                  <name>dfs.namenode.name.dir</name>
                  <value>/opt/hadoop/data/namenode</value>
              </property>
              <property>
                  <name>dfs.d
