---
- name: Install kURL on Ubuntu and configure firewall
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/9420c3b"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Download and execute the kURL installation script
      expect:
        command: curl -sSL {{ kurl_url }} | sudo -S bash
        responses:
          'password for': "{{ sudo_password }}"
          'Would you like to continue? [Y/n]': 'y'
      args:
        chdir: /tmp
      register: install_result
      ignore_errors: yes

    - name: Allow port 6443 through the firewall
      command: sudo ufw allow 6443
      register: ufw_result

    - name: Display firewall configuration result
      debug:
        var: ufw_result.stdout

    - name: Display kURL installation result
      debug:
        var: install_result.stdout
