---
- name: Configure environment variables for Hadoop
  hosts: all
  become: yes
  tasks:
    - name: Ajouter HADOOP_HOME et PATH dans /etc/environment
      blockinfile:
        path: /etc/environment
        block: |
          HADOOP_HOME=/usr/local/hadoop
          PATH="/usr/local/hadoop/bin:/usr/local/hadoop/sbin:{{ ansible_env.PATH }}"
