---
- name: Configure proxy and Install Hadoop 3.4.1
  hosts: all
  become: yes
  vars:
    hadoop_user: "hadoop"
    hadoop_group: "hadoop"
    hadoop_home: "/usr/local/hadoop"
    java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    hadoop_url: "https://downloads.apache.org/hadoop/common/stable/hadoop-3.4.1.tar.gz"
    slave_ip: "morpehus[instance][containers].findAll{it.containerTypeShortName == 'slave'}.collect{it.externalIp}"
    proxy_url: "http://10.1.38.2:3128"

  tasks:
    ## 🟢 Étape 1 : Configuration du proxy
    - name: Configure HTTP proxy for apt
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    ## 🟢 Étape 2 : Mise à jour du système et installation de Java
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name:
          - default-jdk
          - default-jre
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout_lines }}"

    ## 🟢 Étape 3 : Création de l'utilisateur Hadoop et gestion des permissions
    - name: Ensure hadoop group exists
      group:
        name: "{{ hadoop_group }}"
        state: present

    - name: Ensure hadoop user exists
      user:
        name: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ hadoop_user }}"

    - name: Ensure Hadoop user has sudo privileges
      copy:
        dest: "/etc/sudoers.d/hadoop"
        content: "{{ hadoop_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"

    ## 🟢 Étape 4 : Configuration de l'accès SSH sans mot de passe pour Hadoop
    - name: Ensure .ssh directory exists for hadoop user
      file:
        path: "/home/{{ hadoop_user }}/.ssh"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: "0700"

    - name: Generate SSH key for Hadoop user if not exists
      command: "ssh-keygen -t rsa -N '' -f /home/{{ hadoop_user }}/.ssh/id_rsa"
      args:
        creates: "/home/{{ hadoop_user }}/.ssh/id_rsa"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Add SSH public key to authorized_keys
      shell: "cat /home/{{ hadoop_user }}/.ssh/id_rsa.pub >> /home/{{ hadoop_user }}/.ssh/authorized_keys"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Set correct permissions on SSH files
      file:
        path: "/home/{{ hadoop_user }}/.ssh/authorized_keys"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: "0600"

    ## 🟢 Étape 5 : Téléchargement et Installation de Hadoop 3.4.1
    - name: Ensure /usr/local exists
      file:
        path: "/usr/local"
        state: directory
        mode: "0755"

    - name: Download Hadoop 3.4.1
      get_url:
        url: "{{ hadoop_url }}"
        dest: "/tmp/hadoop.tar.gz"
      retries: 3
      delay: 10
      register: download_result
      until: download_result is succeeded

    - name: Extract Hadoop
      unarchive:
        src: "/tmp/hadoop.tar.gz"
        dest: "/usr/local/"
        remote_src: yes

    - name: Rename Hadoop directory
      command: mv /usr/local/hadoop-3.4.1 /usr/local/hadoop
      args:
        removes: /usr/local/hadoop-3.4.1
        creates: "{{ hadoop_home }}"

    - name: Change ownership of Hadoop directory
      file:
        path: "{{ hadoop_home }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        recurse: yes

    ## 🟢 Étape 6 : Configuration des variables d'environnement Hadoop
    - name: Set Hadoop environment variables in .bashrc
      blockinfile:
        path: "/home/{{ hadoop_user }}/.bashrc"
        block: |
          export HADOOP_HOME={{ hadoop_home }}
          export HADOOP_INSTALL=$HADOOP_HOME
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

    - name: Apply environment changes
      shell: |
        sudo -u {{ hadoop_user }} bash -c 'source /home/{{ hadoop_user }}/.bashrc'
