---
- name: Configure environment variables for Hadoop
  hosts: all
  become: yes
  tasks:
    - name: Ajouter les variables d'environnement Hadoop à .bashrc
      lineinfile:
        path: ~/.bashrc
        line: |
          export HADOOP_HOME=/usr/local/hadoop
          export HADOOP_INSTALL=$HADOOP_HOME
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
        state: present

    - name: Recharger le fichier .bashrc pour appliquer les modifications
      shell: source ~/.bashrc
      args:
        executable: /bin/bash
