---
- name: Full System Update and Install kURL on Ubuntu 22
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    kurl_path: "/usr/local/bin/kurl"

  tasks:
    - name: Remove invalid Kubernetes repository (if exists)
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent
      ignore_errors: yes

    - name: Clean APT cache
      command: sudo apt-get clean

    - name: Update APT package list
      apt:
        update_cache: yes

    - name: Upgrade all installed packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install required dependencies (curl, apt-transport-https)
      apt:
        name:
          - curl
          - apt-transport-https
        state: present

    - name: Download kURL script
      get_url:
        url: "{{ kurl_url }}"
        dest: /tmp/kurl.sh
        mode: '0755'

    - name: Run the kURL installation script with automatic confirmation
      shell: |
        yes | sudo bash /tmp/kurl.sh
      args:
        creates: "{{ kurl_path }}"
        
    - name: Check if kURL is installed
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Display kURL version
      debug:
        var: kurl_version.stdout
