---
- name: Install and Configure Kubernetes Worker Node using kURL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"

  tasks:

    # 1️⃣ Configure Proxy for APT (Ubuntu Only)
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    # 2️⃣ Configure Proxy for System Environment
    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    # 3️⃣ Update System Packages
    - name: Update APT package index (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        update_cache: yes

    # 4️⃣ Install Required Dependencies
    - name: Install required dependencies for Kubernetes (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        name: 
          - curl 
          - tar 
          - socat 
          - jq 
          - iptables 
        state: present

    # 5️⃣ Configure DNS (nameserver)
    - name: Add Google DNS to resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: 'nameserver 8.8.8.8'

    - name: Set persistent DNS via resolved.conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^DNS='
        line: 'DNS=8.8.8.8'

    - name: Restart systemd-resolved service
      ansible.builtin.systemd:
        name: systemd-resolved
        state: restarted

    - name: Verify resolv.conf contains 8.8.8.8
      command: cat /etc/resolv.conf
      register: resolv_conf_output

    - debug:
        msg: "resolv.conf content: {{ resolv_conf_output.stdout }}"

    # 6️⃣ Disable Swap
    - name: Disable swap
      ansible.builtin.command: swapoff -a

    - name: Ensure swap is disabled permanently
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    # 7️⃣ Load Required Kernel Modules
    - name: Load required kernel modules
      ansible.builtin.shell: |
        modprobe br_netfilter
        modprobe overlay

    - name: Ensure br_netfilter and overlay modules are loaded on system boot
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    # 8️⃣ Set System Configuration for Kubernetes Networking
    - name: Set sysctl parameters for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl parameters
      ansible.builtin.command: sysctl --system

    # 9️⃣ Install Kubernetes via kURL (new method)
    - name: Download kURL installer script
      ansible.builtin.get_url:
        url: https://kurl.sh/latest
        dest: /tmp/kurl_installer.sh
        mode: '0755'

    - name: Run the kURL installer script
      ansible.builtin.shell: |
        bash /tmp/kurl_installer.sh
      args:
        creates: /etc/kurl

    - name: Clean up the kURL installer script
      ansible.builtin.file:
        path: /tmp/kurl_installer.sh
        state: absent

    # 🔟 Join the Kubernetes Worker Node to the Cluster
    - name: Join the worker node to the Kubernetes cluster
      ansible.builtin.shell: |
        if [ -f /root/join-command.sh ]; then
          bash /root/join-command.sh
        else
          echo "Join command not found. Ensure it is created on the master."
        fi
