---
- name: Installer WordPress sur Ubuntu
  hosts: web
  become: yes
  tasks:

    - name: Mettre à jour le système
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer Apache, MySQL, PHP et dépendances
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - unzip
          - wget
        state: present

    - name: Démarrer Apache et MySQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Sécuriser MySQL (désactiver l'authentification par socket pour root)
      mysql_user:
        name: root
        host: localhost
        password: rootroot
        login_user: root
        login_password: rootroot
        priv: "*.*:ALL,GRANT"

    - name: Créer une base de données WordPress
      mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: rootroot

    - name: Créer un utilisateur MySQL pour WordPress
      mysql_user:
        name: wp_user
        password: wp_pass
        priv: "wordpress.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: rootroot

    - name: Télécharger WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extraire WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Modifier les permissions de WordPress
      file:
        path: /var/www/html/wordpress
        owner: www-data
        group: www-data
        mode: "0755"
        recurse: yes

    - name: Copier le fichier de configuration wp-config.php
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Redémarrer Apache
      service:
        name: apache2
        state: restarted
