---
- name: Installer kURL
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/9420c3b"

  tasks:
    - name: Télécharger et exécuter le script d'installation kURL
      shell: |
        curl {{ kurl_url }} | sudo bash
      register: install_result
      ignore_errors: no

    - name: Vérifier le résultat de l'installation
      debug:
        var: install_result.stdout

    - name: Mettre à jour le logiciel
      expect:
        command: vsx update-software
        responses:
          'would you like to continue': 'y'

