---
- name: Install and Configure Hadoop 3.4.1 (Lean)
  hosts: all
  become: yes
  vars:
    hadoop_user: "hadoop"
    hadoop_group: "hadoop"
    hadoop_home: "/usr/local/hadoop"
    java_home: "/usr/lib/jvm/java-11-openjdk-amd64"
    hadoop_url: "https://downloads.apache.org/hadoop/common/stable/hadoop-3.4.1-lean.tar.gz"

  tasks:

    ## 🟢 Étape 1 : Mise à jour du système et installation de Java
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name:
          - default-jdk
          - default-jre
        state: present

    - name: Verify Java installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "{{ java_version.stdout_lines }}"

    ## 🟢 Étape 2 : Création de l'utilisateur Hadoop et gestion des permissions
    - name: Ensure hadoop group exists
      group:
        name: "{{ hadoop_group }}"
        state: present

    - name: Ensure hadoop user exists
      user:
        name: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        shell: /bin/bash
        createhome: yes
        home: "/home/{{ hadoop_user }}"

    - name: Ensure Hadoop user has sudo privileges
      copy:
        dest: "/etc/sudoers.d/hadoop"
        content: "{{ hadoop_user }} ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"

    ## 🟢 Étape 3 : Correction des permissions des fichiers temporaires Ansible
    - name: Fix temporary directory permissions for Ansible
      command: mkdir -p /tmp/.ansible/tmp && chmod 777 /tmp/.ansible/tmp

    ## 🟢 Étape 4 : Téléchargement et Installation de Hadoop 3.4.1-lean
    - name: Ensure /usr/local exists
      file:
        path: "/usr/local"
        state: directory
        mode: "0755"

    - name: Download Hadoop 3.4.1-lean
      get_url:
        url: "{{ hadoop_url }}"
        dest: "/tmp/hadoop.tar.gz"
      retries: 3
      delay: 10
      register: download_result
      until: download_result is succeeded

    - name: Extract Hadoop
      unarchive:
        src: "/tmp/hadoop.tar.gz"
        dest: "/usr/local/"
        remote_src: yes

    - name: Rename Hadoop directory
      command: mv /usr/local/hadoop-3.4.1-lean /usr/local/hadoop
      args:
        removes: /usr/local/hadoop-3.4.1-lean
        creates: "{{ hadoop_home }}"

    - name: Change ownership of Hadoop directory
      file:
        path: "{{ hadoop_home }}"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        recurse: yes

    ## 🟢 Étape 5 : Configuration des variables d'environnement Hadoop
    - name: Set Hadoop environment variables in .bashrc
      blockinfile:
        path: "/home/{{ hadoop_user }}/.bashrc"
        block: |
          export HADOOP_HOME={{ hadoop_home }}
          export HADOOP_INSTALL=$HADOOP_HOME
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export YARN_HOME=$HADOOP_HOME
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
          export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"

    - name: Apply environment changes
      shell: source /home/{{ hadoop_user }}/.bashrc
      become_user: "{{ hadoop_user }}"

    ## 🟢 Étape 6 : Configuration de Java dans Hadoop
    - name: Set JAVA_HOME in Hadoop environment
      lineinfile:
        path: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"
        regexp: '^export JAVA_HOME='
        line: 'export JAVA_HOME={{ java_home }}'
        state: present

    ## 🟢 Étape 7 : Vérification de l'installation de Hadoop
    - name: Check Hadoop version
      command: "{{ hadoop_home }}/bin/hadoop version"
      register: hadoop_version
      changed_when: false

    - name: Display Hadoop version
      debug:
        msg: "{{ hadoop_version.stdout_lines }}"
