---
- name: Install Java for Hadoop
  hosts: all
  become: yes
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Ensure JAVA_HOME is set in /etc/environment
      lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
        state: present
