---
- name: Download and Extract Hadoop
  hosts: all
  become: yes
  vars:
    hadoop_version: "3.4.0"
    hadoop_download_url: "https://dlcdn.apache.org/hadoop/common/hadoop-3.4.0/hadoop-3.4.0.tar.gz"
    download_path: "/home/hadoop"
  
  tasks:
    ## 🟢 Étape 1 : Télécharger Hadoop
    - name: Download Hadoop {{ hadoop_version }}
      get_url:
        url: "{{ hadoop_download_url }}"
        dest: "{{ download_path }}/hadoop-{{ hadoop_version }}.tar.gz"
        mode: "0644"

    ## 🟢 Étape 2 : Extraire Hadoop
    - name: Extract Hadoop Archive
      ansible.builtin.unarchive:
        src: "{{ download_path }}/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "{{ download_path }}/"
        remote_src: yes
