---
- name: Configure Passwordless SSH for Hadoop on Ubuntu
  hosts: all
  become: yes
  tasks:
    
    # 1. Install OpenSSH server (only for Ubuntu/Debian)
    - name: Install OpenSSH server
      apt:
        name: openssh-server
        state: present
        update_cache: yes

    # 2. Check if SSH key pair exists; if not, generate one
    - name: Generate SSH key pair if not already present
      command: ssh-keygen -t rsa -f "{{ ansible_env.HOME }}/.ssh/id_rsa" -q -N ""
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/id_rsa"

    # 3. Copy the public key to authorized_keys (use absolute path to id_rsa.pub)
    - name: Add SSH key to authorized_keys
      copy:
        src: "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
        dest: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'

    # 4. Set proper permissions for the .ssh directory
    - name: Set permissions for .ssh directory
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    # 5. Test passwordless SSH to localhost
    - name: Test passwordless SSH to localhost
      command: ssh -o StrictHostKeyChecking=no localhost hostname
      register: ssh_test
      ignore_errors: yes

    # 6. Display the results of the SSH test
    - name: Show passwordless SSH test results
      debug:
        msg: "SSH connection successful: {{ ssh_test.stdout }}"
