---
- name: Configure Passwordless SSH for Hadoop
  hosts: all
  become: yes
  tasks:
    # 1. Generate SSH key pair if not already present
    - name: Generate SSH key pair
      command: ssh-keygen -t rsa -f /home/{{ ansible_user }}/.ssh/id_rsa -q -N ""
      args:
        creates: "/home/{{ ansible_user }}/.ssh/id_rsa"

    # 2. Copy public key to authorized_keys
    - name: Add SSH key to authorized_keys
      copy:
        src: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"  # Fichier sur la machine distante
        dest: "/home/{{ ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
        remote_src: yes  # Indiquer que le fichier source est sur la machine distante

    # 3. Ensure proper permissions for .ssh directory
    - name: Set permissions for .ssh directory
      file:
        path: "/home/{{ ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0700'

    # 4. Test SSH connectivity to localhost
    - name: Test passwordless SSH to localhost
      command: ssh -o StrictHostKeyChecking=no localhost hostname
      register: ssh_test
      ignore_errors: yes

    # 5. Display SSH test results
    - name: Show passwordless SSH test results
      debug:
        msg: "SSH connection successful: {{ ssh_test.stdout }}"
