---
- name: Install kURL on Ubuntu 22
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"

  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Download and install kURL
      shell: |
        yes | curl -sSL {{ kurl_url }} | sudo bash
      args:
        chdir: /tmp
        creates: /usr/local/bin/kurl

    - name: Check if kURL is installed
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Display kURL version
      debug:
        var: kurl_version.stdout
