---
- name: Installer Kurl sur Ubuntu
  hosts: all
  become: yes  # Exécuter en tant que root
  tasks:
    - name: Vérifier que l'OS est Ubuntu
      fail:
        msg: "Ce playbook est conçu uniquement pour Ubuntu."
      when: ansible_facts['distribution'] != "Ubuntu"

    - name: Définir un répertoire temporaire sécurisé pour Ansible
      ansible.builtin.file:
        path: /tmp/.ansible/tmp
        state: directory
        mode: '0700'
        owner: "{{ ansible_user | default('ubuntu') }}"
        group: "{{ ansible_user | default('ubuntu') }}"

    - name: Forcer Ansible à utiliser /tmp comme répertoire temporaire
      set_fact:
        ansible_remote_tmp: "/tmp/.ansible/tmp"

    - name: Mettre à jour les paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les dépendances requises
      ansible.builtin.apt:
        name:
          - curl
          - sudo
        state: present

    - name: Télécharger et exécuter le script d'installation de Kurl
      ansible.builtin.shell: "curl https://kurl.sh/f2e5eda | sudo bash"
      args:
        executable: /bin/bash
      register: kurl_installation

    - name: Afficher la sortie de l'installation
      debug:
        var: kurl_installation.stdout_lines
