---
- name: Installer kURL
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/9420c3b"

  tasks:
    - name: Télécharger le script d'installation kURL
      shell: |
        curl {{ kurl_url }} -o /tmp/kurl.sh
      args:
        executable: /bin/bash
        creates: /tmp/kurl.sh

    - name: Rendre le script exécutable
      file:
        path: /tmp/kurl.sh
        mode: '0755'

    - name: Exécuter le script d'installation kURL
      shell: |
        sudo /tmp/kurl.sh
      args:
        executable: /bin/bash
      register: install_result
      ignore_errors: no

    - name: Vérifier le résultat de l'installation
      debug:
        var: install_result.stdout

    - name: Ouvrir le port 6443 pour Kubernetes
      command: sudo ufw allow 6443
