---
- name: Configure environment variables for Hadoop
  hosts: all
  become: yes
  tasks:
    - name: Ajouter les variables d'environnement Hadoop à .bashrc
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: |
          export HADOOP_HOME=/usr/local/hadoop
          export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin
        state: present

    - name: Recharger le fichier .bashrc pour appliquer les modifications
      shell: source /home/{{ ansible_user }}/.bashrc
      args:
        executable: /bin/bash
