---
- hosts: all
  become: true

  tasks:
    - name: Mettre à jour le système et installer les prérequis
      apt:
        name: aptitude
        update_cache: yes
        state: latest
        force_apt_get: yes
      tags: [ system ]

    - name: Installer le serveur LAMP
      apt:
        name:
          - apache2
          - mysql-server
          - python3-pymysql
          - php
          - php-mysql
          - libapache2-mod-php
        update_cache: yes
        state: latest
      tags: [ system ]

  # Configuration Apache
    - name: Créer le répertoire du site
      file:
        path: "/var/www/html"
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: '0755'
      tags: [ apache ]

    - name: Activer le module rewrite d'Apache
      shell: /usr/sbin/a2enmod rewrite
      notify: Reload Apache
      tags: [ apache ]

    - name: Désactiver le site par défaut d'Apache
      shell: /usr/sbin/a2dissite 000-default.conf
      notify: Restart Apache
      tags: [ apache ]

  # Configuration MySQL
    - name: Définir le mot de passe root de MySQL
      community.mysql.mysql_user:
        name: root
        password: rootroot
        login_unix_socket: /var/run/mysqld/mysqld.sock
      tags: [ mysql ]

    - name: Supprimer les utilisateurs anonymes de MySQL
      community.mysql.mysql_user:
        name: ''
        host_all: yes
        state: absent
        login_user: root
        login_password: rootroot
      tags: [ mysql ]

    - name: Supprimer la base de données de test
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: rootroot
      tags: [ mysql ]

    - name: Créer la base de données WordPress
      community.mysql.mysql_db:
        name: wordpress
        state: present
        login_user: root
        login_password: rootroot
      tags: [ mysql ]

    - name: Créer l'utilisateur MySQL pour WordPress
      community.mysql.mysql_user:
        name: wp_user
        password: wp_pass
        priv: "wordpress.*:ALL"
        state: present
        login_user: root
        login_password: rootroot
      tags: [ mysql ]

  # Configuration WordPress
    - name: Télécharger et extraire WordPress
      unarchive:
        src: https://wordpress.org/latest.tar.gz
        dest: "/var/www/html"
        remote_src: yes
        creates: "/var/www/html/wordpress"
      tags: [ wordpress ]

    - name: Changer les permissions de WordPress
      file:
        path: "/var/www/html/wordpress"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
      tags: [ wordpress ]

    - name: Définir les permissions des dossiers WordPress
      shell: "/usr/bin/find /var/www/html/wordpress/ -type d -exec chmod 750 {} \\;"
      tags: [ wordpress ]

    - name: Définir les permissions des fichiers WordPress
      shell: "/usr/bin/find /var/www/html/wordpress/ -type f -exec chmod 640 {} \\;"
      tags: [ wordpress ]

    - name: Copier wp-config.php
      template:
        src: "files/wp-config.php.j2"
        dest: "/var/www/html/wordpress/wp-config.php"
      tags: [ wordpress ]

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
