---
- name: Installer kURL sur Ubuntu 22 de manière robuste
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    script_path: "/tmp/kurl_install.sh"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Mettre à jour la liste des paquets APT
      apt:
        update_cache: yes

    - name: Installer curl si non présent
      apt:
        name: curl
        state: present

    - name: Télécharger le script d'installation de kURL
      get_url:
        url: "{{ kurl_url }}"
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Exécuter le script d'installation de kURL
      shell: |
        echo "{{ sudo_password }}" | sudo -S bash -c "yes | {{ script_path }}"
      args:
        executable: /bin/bash

    - name: Vérifier si kURL est installé
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Afficher la version de kURL si elle est installée
      debug:
        var: kurl_version.stdout

    - name: Nettoyer le fichier script téléchargé
      file:
        path: "{{ script_path }}"
        state: absent
