- name: Configure Hadoop XML files locally
  hosts: localhost
  tasks:
    - name: Configurer core-site.xml
      copy:
        dest: "/usr/local/hadoop/etc/hadoop/core-site.xml"
        content: |
          <configuration>
            <property>
              <name>fs.defaultFS</name>
              <value>hdfs://localhost:9000</value>
            </property>
          </configuration>
