---
- name: Installer kURL sur Ubuntu
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Mettre à jour les paquets APT
      shell: |
        echo "{{ sudo_password }}" | sudo -S apt update && sudo -S apt upgrade -y
      args:
        executable: /bin/bash

    - name: Installer curl et wget
      shell: |
        echo "{{ sudo_password }}" | sudo -S apt install -y curl wget
      args:
        executable: /bin/bash

    - name: Télécharger et exécuter le script d'installation kURL
      shell: |
        echo "{{ sudo_password }}" | sudo -S bash -c "curl -sSL {{ kurl_url }} | bash"
      args:
        executable: /bin/bash
      register: install_result
      ignore_errors: yes

    - name: Vérifier le résultat de l'installation
      debug:
        var: install_result.stdout
