---
- name: Installer Kurl sur Ubuntu
  hosts: all
  become: yes  # Exécuter avec sudo
  tasks:
    - name: Vérifier que l'OS est Ubuntu
      fail:
        msg: "Ce playbook est conçu uniquement pour Ubuntu."
      when: ansible_facts['distribution'] != "Ubuntu"

    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: yes

    - name: Installer les dépendances requises
      ansible.builtin.apt:
        name:
          - curl
          - sudo
        state: present

    - name: Télécharger et exécuter le script d'installation de Kurl
      ansible.builtin.shell: "curl https://kurl.sh/f2e5eda | sudo bash"
      args:
        executable: /bin/bash
      register: kurl_installation

    - name: Afficher la sortie de l'installation
      debug:
        var: kurl_installation.stdout_lines
