---
- name: Install WordPress on Ubuntu
  hosts: all
  become: yes
  vars:
    mysql_root_password: rootroot
    mysql_user: root
    mysql_password: rootroot
    mysql_database: wordpress_db
    http_host: your_domain
    http_conf: your_domain.conf
    http_port: "80"
    disable_default: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install LAMP packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - python3-pymysql
        state: present

    - name: Start and enable Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        login_user: root
        check_implicit_admin: yes

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_database }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions for WordPress directory
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Copy WordPress config file
      template:
        src: /var/www/html/wordpress/wp-config-sample.php
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data

    - name: Update WordPress config file
      replace:
        path: /var/www/html/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - { regexp: 'database_name_here', replace: "{{ mysql_database }}" }
        - { regexp: 'username_here', replace: "{{ mysql_user }}" }
        - { regexp: 'password_here', replace: "{{ mysql_password }}" }

    - name: Generate WordPress salts
      shell: curl -s https://api.wordpress.org/secret-key/1.1/salt/
      register: wp_salts
      changed_when: false

    - name: Add WordPress salts to config file
      blockinfile:
        path: /var/www/html/wordpress/wp-config.php
        block: "{{ wp_salts.stdout }}"
        marker: "// ANSIBLE MANAGED BLOCK"
        insertafter: "/* Add any custom values between this line and the \"stop editing\" line. */"

    - name: Create Apache virtual host
      template:
        src: /etc/apache2/sites-available/000-default.conf
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
        owner: root
        group: root
        mode: '0644'

    - name: Enable Apache rewrite module
      apache2_module:
        name: rewrite
        state: present

    - name: Enable new site
      shell: |
        a2ensite {{ http_conf }}
        a2enmod rewrite
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
