---
- name: Installer kURL sur Ubuntu 22 et corriger les dépendances
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Corriger les dépendances cassées
      shell: |
        echo "{{ sudo_password }}" | sudo -S apt --fix-broken install -y
      register: fix_broken_output
      ignore_errors: yes

    - name: Afficher la sortie de la correction des dépendances
      debug:
        var: fix_broken_output.stdout_lines

    - name: Mettre à jour et upgrader les paquets APT
      apt:
        upgrade: dist
        state: latest
      ignore_errors: yes

    - name: Installer curl
      apt:
        name: curl
        state: present

    - name: Télécharger et installer kURL
      shell: |
        echo "{{ sudo_password }}" | sudo -S bash -c "yes | curl -sSL {{ kurl_url }} | bash"
      args:
        chdir: /tmp
        creates: /usr/local/bin/kurl

    - name: Vérifier si kURL est installé
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Afficher la version de kURL
      debug:
        var: kurl_version.stdout
