---
- name: Installer kURL sur Ubuntu 22 avec mot de passe sudo
  hosts: all
  become: yes
  vars:
    kurl_url: "https://kurl.sh/3e386c9"
    sudo_password: "ACSCloud!2021!"

  tasks:
    - name: Mettre à jour les paquets APT
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installer curl
      apt:
        name: curl
        state: present

    - name: Télécharger et installer kURL avec confirmation automatique
      shell: |
        echo "{{ sudo_password }}" | sudo -S bash -c "yes | curl -sSL {{ kurl_url }} | bash"
      args:
        chdir: /tmp
        creates: /usr/local/bin/kurl

    - name: Vérifier si kURL est installé
      command: kurl --version
      register: kurl_version
      ignore_errors: yes

    - name: Afficher la version de kURL
      debug:
        var: kurl_version.stdout
