---
- name: Configure Kubernetes Worker Node on Ubuntu using kURL
  hosts: all
  become: true
  vars:
    proxy_url: "http://10.1.38.2:3128"

  tasks:
    - name: Configure HTTP proxy for apt
      when: ansible_distribution == "Ubuntu"
      copy:
        content: |
          Acquire::http::Proxy "{{ proxy_url }}";
          Acquire::https::Proxy "{{ proxy_url }}";
        dest: /etc/apt/apt.conf.d/95proxies

    - name: Configure HTTP proxy for the environment
      lineinfile:
        path: /etc/environment
        line: '{{ item }}'
        create: yes
      with_items:
        - 'http_proxy={{ proxy_url }}'
        - 'https_proxy={{ proxy_url }}'
        - 'HTTP_PROXY={{ proxy_url }}'
        - 'HTTPS_PROXY={{ proxy_url }}'

    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required dependencies
      ansible.builtin.apt:
        name: 
          - curl 
          - tar 
          - socat 
          - jq 
          - iptables 
        state: present

    - name: Disable swap
      ansible.builtin.command: swapoff -a

    - name: Ensure swap is disabled permanently
      ansible.builtin.lineinfile:
        path: /etc/fstab
        regexp: '.*swap.*'
        state: absent

    - name: Load required kernel modules
      ansible.builtin.shell: |
        modprobe br_netfilter
        modprobe overlay

    - name: Ensure br_netfilter and overlay modules are loaded
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    - name: Set sysctl params for Kubernetes
      ansible.builtin.copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl parameters
      ansible.builtin.command: sysctl --system

    - name: Download kURL installer for worker node
      ansible.builtin.shell: |
        curl -fsSL https://kurl.sh/latest | sudo bash

    - name: Join Kubernetes cluster using token from master
      ansible.builtin.shell: |
        if [ -f /root/join-command.sh ]; then
          bash /root/join-command.sh
        else
          echo "Join command not found. Ensure it is created on the master."
        fi
