---
- name: Install Zabbix on Ubuntu and RHEL
  hosts: all
  become: true
  vars:
    rhel_username: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelEmail'] | default('') }}"
    rhel_password: "{{ hostvars[inventory_hostname]['morpheus']['customOptions']['rhelPw'] | default('') }}"
    zabbix_db_password: "zabbix123"
    postgres_password: "{{ hostvars[inventory_hostname].get('morpheus', {}).get('customOptions', {}).get('dbCustomPassword', 'postgres123') }}"
    ansible_remote_tmp: "/var/tmp/.ansible/tmp"

  tasks:
    # DNS configuration for both Ubuntu and RHEL
    - name: Configure resolv.conf with Google DNS (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    - name: Configure resolv.conf with Google DNS (RHEL)
      when: ansible_os_family == "RedHat"
      shell: echo nameserver 8.8.8.8 > /etc/resolv.conf
    
    # Clear proxy settings
    - name: Clear apt proxy settings (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: echo > /etc/apt/apt.conf.d/90curtin-aptproxy
    
    - name: Clear yum proxy settings (RHEL)
      when: ansible_os_family == "RedHat"
      shell: echo > /etc/yum.conf.d/90curtin-aptproxy
    
    # Ubuntu-specific tasks
    - name: Download Zabbix release package (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb

    - name: Install Zabbix release package (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Update apt cache (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        update_cache: yes

    - name: Install Zabbix packages (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      apt:
        name:
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
      register: zabbix_install_ubuntu

    # RHEL-specific tasks
    - name: Register and subscribe RHEL system
      when: ansible_os_family == "RedHat"
      command: subscription-manager register --username {{ rhel_username }} --password {{ rhel_password }} --auto-attach
      register: subscription_result
      failed_when: subscription_result.rc != 0 and 'This system is already registered' not in subscription_result.stderr
      changed_when: subscription_result.rc == 0

    - name: Install Zabbix repository (RHEL)
      when: ansible_os_family == "RedHat"
      yum:
        name: https://repo.zabbix.com/zabbix/7.0/rhel/8/x86_64/zabbix-release-latest.el8.noarch.rpm
        state: present
        disable_gpg_check: yes

    - name: Switch PHP module to 8.2 (RHEL)
      when: ansible_os_family == "RedHat"
      command: dnf module switch-to php:8.2 -y

    - name: Install Zabbix packages (RHEL)
      when: ansible_os_family == "RedHat"
      dnf:
        name:
          - zabbix-server-pgsql
          - zabbix-web-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-selinux-policy
          - zabbix-agent
        state: present
      register: zabbix_install_rhel

    # PostgreSQL database setup for Zabbix
    - name: Configure PostgreSQL authentication (RHEL)
      lineinfile:
        path: /var/lib/pgsql/data/pg_hba.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      with_items:
        - { regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+ident', line: 'host    all             all             127.0.0.1/32            md5' }
        - { regexp: '^local\s+all\s+all\s+peer', line: 'local   all             all                                     md5' }
      when: ansible_os_family == "RedHat"

    - name: Get PostgreSQL version (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      shell: ls -1 /etc/postgresql/ | sort -V | tail -n 1
      register: pg_version
      changed_when: false

    - name: Configure PostgreSQL authentication (Ubuntu)
      lineinfile:
        path: "/etc/postgresql/{{ pg_version.stdout }}/main/pg_hba.conf"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      with_items:
        - { regexp: '^host\s+all\s+all\s+127.0.0.1/32\s+peer', line: 'host    all             all             127.0.0.1/32            md5' }
        - { regexp: '^local\s+all\s+all\s+peer', line: 'local   all             all                                     md5' }
      when: ansible_distribution == "Ubuntu"

    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted

    # PostgreSQL database setup for Zabbix
    - name: Create Zabbix database user
      become: yes
      become_user: postgres
      shell: |
        psql -c "CREATE USER zabbix WITH PASSWORD '{{ zabbix_db_password }}';"
      args:
        chdir: /tmp
      register: create_user_result
      ignore_errors: yes

    - name: Create Zabbix database
      become: yes
      become_user: postgres
      shell: |
        psql -c "CREATE DATABASE zabbix OWNER zabbix;"
      args:
        chdir: /tmp
      register: create_db_result
      ignore_errors: yes

    - name: Grant privileges to Zabbix user
      become: yes
      become_user: postgres
      shell: |
        psql -c "GRANT ALL PRIVILEGES ON DATABASE zabbix TO zabbix;"
      args:
        chdir: /tmp
      register: grant_privileges
      ignore_errors: yes

    - name: Import Zabbix schema
      become: yes
      become_user: postgres
      shell: |
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql zabbix
      register: schema_import
      changed_when: schema_import.rc == 0
      failed_when: schema_import.rc != 0

    - name: Configure Zabbix server database connection
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^DBHost=', line: 'DBHost=localhost' }
        - { regexp: '^DBName=', line: 'DBName=zabbix' }
        - { regexp: '^DBUser=', line: 'DBUser=zabbix' }
        - { regexp: '^DBPassword=', line: 'DBPassword={{ zabbix_db_password }}' }

    # Configure PHP for Zabbix frontend
    - name: Set PHP timezone (Ubuntu)
      lineinfile:
        path: /etc/php/8.1/apache2/php.ini
        regexp: "^;?date.timezone ="
        line: "date.timezone = UTC"
      when: ansible_distribution == "Ubuntu"

    - name: Set PHP timezone (RHEL)
      lineinfile:
        path: /etc/php.ini
        regexp: "^;?date.timezone ="
        line: "date.timezone = UTC"
      when: ansible_os_family == "RedHat"

    # Configure Apache for Zabbix
    - name: Configure Apache for Zabbix
      copy:
        dest: /etc/zabbix/apache.conf
        content: |
          Alias /zabbix /usr/share/zabbix
          
          <Directory "/usr/share/zabbix">
              Options FollowSymLinks
              AllowOverride None
              Require all granted
              
              <IfModule mod_php.c>
                  php_value max_execution_time 300
                  php_value memory_limit 128M
                  php_value post_max_size 16M
                  php_value upload_max_filesize 2M
                  php_value max_input_time 300
                  php_value max_input_vars 10000
                  php_value always_populate_raw_post_data -1
              </IfModule>
          </Directory>

    # Start services for Ubuntu
    - name: Start Zabbix services (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - apache2

    # Start services for RHEL
    - name: Start Zabbix services (RHEL)
      when: ansible_os_family == "RedHat"
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - zabbix-server
        - zabbix-agent
        - httpd
        - php-fpm

    - name: Wait for Zabbix web interface
      uri:
        url: http://localhost/zabbix/
        status_code: 200
        timeout: 300
      register: result
      until: result.status == 200
      retries: 60
      delay: 5
      ignore_errors: yes

    - name: Clean up downloaded files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/zabbix-release.deb
      ignore_errors: yes

    - name: Print installation complete message
      debug:
        msg: 
          - "Zabbix has been installed successfully."
          - "Access Zabbix at http://{{ morpheus['server']['internalIp'] }}/zabbix"
          - "Default credentials:"
          - "Username: Admin"
          - "Password: zabbix"
