---
- name: Install Zabbix 7.0
  hosts: all
  vars:
    proxy_url: "http://10.1.38.2:3128"
    mysql_root_password: "Password123@"
    zabbix_db_password: "Password123@"
    sudo_password: "{{ lookup('cypher','secret=secret/pw') }}"
  tasks:
    - name: Configure HTTP proxy for the environment
      shell: |
        echo 'export http_proxy={{ proxy_url }}' | echo "{{ sudo_password }}" | sudo -S tee -a /etc/environment
        echo 'export https_proxy={{ proxy_url }}' | echo "{{ sudo_password }}" | sudo -S tee -a /etc/environment
        echo 'Acquire::http::Proxy "{{ proxy_url }}";' | echo "{{ sudo_password }}" | sudo -S tee /etc/apt/apt.conf.d/95proxies

    - name: Update apt cache and install prerequisites
      shell: |
        echo "{{ sudo_password }}" | sudo -S apt update && echo "{{ sudo_password }}" | sudo -S apt install -y wget lsb-release gnupg mysql-server

    - name: Download and install Zabbix repository
      shell: |
        wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu$(lsb_release -rs)_all.deb
        echo "{{ sudo_password }}" | sudo -S dpkg -i zabbix-release_latest+ubuntu$(lsb_release -rs)_all.deb
        echo "{{ sudo_password }}" | sudo -S apt update

    - name: Install Zabbix packages
      shell: |
        echo "{{ sudo_password }}" | sudo -S apt install -y zabbix-server-mysql zabbix-frontend-php zabbix-apache-conf zabbix-agent zabbix-sql-scripts

    - name: Configure MySQL database for Zabbix
      shell: |
        echo "CREATE DATABASE zabbix CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
              CREATE USER 'zabbix'@'localhost' IDENTIFIED BY '{{ zabbix_db_password }}';
              GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';
              SET GLOBAL log_bin_trust_function_creators = 1;" | echo "{{ sudo_password }}" | sudo -S mysql -uroot -p'{{ mysql_root_password }}'

    - name: Import Zabbix database schema
      shell: |
        zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql -uzabbix -p'{{ zabbix_db_password }}' zabbix

    - name: Configure Zabbix server database password
      shell: |
        echo "{{ sudo_password }}" | sudo -S sed -i "s/^# DBPassword=/DBPassword={{ zabbix_db_password }}/" /etc/zabbix/zabbix_server.conf

    - name: Start and enable Zabbix services
      shell: |
        echo "{{ sudo_password }}" | sudo -S systemctl restart zabbix-server zabbix-agent apache2
        echo "{{ sudo_password }}" | sudo -S systemctl enable zabbix-server zabbix-agent apache2

    - name: Cleanup
      shell: echo "{{ sudo_password }}" | sudo -S rm -f zabbix-release_latest+ubuntu$(lsb_release -rs)_all.deb
