---
- name: Installer kURL
  hosts: all
  become: yes
  tasks:
    - name: Télécharger et exécuter le script kURL avec confirmation automatique
      expect:
        command: curl https://kurl.sh/254c595 | sudo bash
        responses:
          'Would you like to continue? [Y/n]': 'y'
