---
- name: Installer zip et mettre à jour 
  hosts: all
  become: yes
  tasks:
    
    - name: Mettre à jour le logiciel
      expect:
        command: sudo apt install zip 
        responses:
          'Do you want to continue?': 'y'
