---
- name: Installer zip et mettre à jour le logiciel
  hosts: all
  become: yes
  tasks:
    
    - name: Mettre à jour le logiciel
      expect:
        command: sudo apt install zip 
        responses:
          'would you like to continue': 'y'
