---
- name: Prepare Hadoop Installation for Ubuntu
  hosts: all
  become: yes
  vars:
    hadoop_user: "hdoop"
    hadoop_group: "hadoopgroup"
    hadoop_home: "/home/hdoop"
    hadoop_version: "3.3.6"
    hadoop_mirrors:
      - "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
      - "https://downloads.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
      - "https://archive.apache.org/dist/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"

  pre_tasks:
    - name: Update Ubuntu apt cache
      apt:
        update_cache: yes

    - name: Install Java and required packages for Ubuntu
      apt:
        name: 
          - default-jdk
          - default-jre
          - wget
          - openssh-server
          - ssh
        state: present

    - name: Ensure group exists
      group:
        name: "{{ hadoop_group }}"
        state: present

    - name: Create Hadoop user
      user:
        name: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        home: "{{ hadoop_home }}"
        shell: /bin/bash
        create_home: yes
        state: present

  tasks:
    - name: Create Hadoop download directory
      file:
        path: "{{ hadoop_home }}/downloads"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"
        mode: '0755'

    - name: Download Hadoop using wget with multiple mirrors
      shell: |
        set -o pipefail
        for mirror in {{ hadoop_mirrors | join(' ') }}; do
          wget --tries=3 \
               --timeout=300 \
               --no-check-certificate \
               -O "{{ hadoop_home }}/downloads/hadoop-{{ hadoop_version }}.tar.gz" \
               "$mirror" && exit 0
        done
        exit 1
      args:
        creates: "{{ hadoop_home }}/downloads/hadoop-{{ hadoop_version }}.tar.gz"
        executable: /bin/bash
      register: wget_download
      changed_when: wget_download.rc == 0
      failed_when: wget_download.rc != 0

    - name: Verify downloaded file
      stat:
        path: "{{ hadoop_home }}/downloads/hadoop-{{ hadoop_version }}.tar.gz"
      register: hadoop_download_file

    - name: Check download file size
      assert:
        that:
          - hadoop_download_file.stat.exists
          - hadoop_download_file.stat.size > 100000000  # Check if file is larger than 100MB
        fail_msg: "Download failed or file is too small"

    - name: Extract Hadoop archive
      unarchive:
        src: "{{ hadoop_home }}/downloads/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "{{ hadoop_home }}"
        remote_src: yes
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"

    - name: Create symbolic link for Hadoop
      file:
        src: "{{ hadoop_home }}/hadoop-{{ hadoop_version }}"
        dest: "{{ hadoop_home }}/hadoop"
        state: link
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_group }}"

    - name: Verify Hadoop installation
      stat:
        path: "{{ hadoop_home }}/hadoop-{{ hadoop_version }}"
      register: hadoop_dir

    - name: Fail if Hadoop directory does not exist
      fail:
        msg: "Hadoop installation failed - directory not found"
      when: not hadoop_dir.stat.exists
