---
- name: Télécharger un fichier avec curl
  hosts: all
  become: yes
  tasks:
    - name: Télécharger le fichier bundle avec curl
      command: curl -LO https://k8s.kurl.sh/bundle/254c595.tar.gz
      
