---
- name: Install Java, SSH, and configure Hadoop user
  hosts: all
  become: yes

  vars:
    hadoop_user: "hdoop"
    hadoop_full_name: "hadoop"
    hadoop_password: "hadoop"

  tasks:
    ## 游릭 Step 1: Update APT package lists
    - name: Update APT package lists
      apt:
        update_cache: yes

    ## 游릭 Step 2: Install OpenJDK 8
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    ## 游릭 Step 3: Verify Java installation
    - name: Check Java and Javac versions
      command: "{{ item }}"
      with_items:
        - java -version
        - javac -version
      register: java_versions
      changed_when: false

    - name: Display Java versions
      debug:
        msg: "{{ java_versions.results | map(attribute='stdout_lines') | list }}"

    ## 游릭 Step 4: Install OpenSSH Server & Client
    - name: Install OpenSSH Server & Client
      apt:
        name:
          - openssh-server
          - openssh-client
        state: present

    ## 游릭 Step 5: Create Hadoop User
    - name: Create Hadoop User
      user:
        name: "{{ hadoop_user }}"
        comment: "{{ hadoop_full_name }}"
        password: "{{ hadoop_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes

    ## 游릭 Step 6: Ensure SSH Directory Exists with Correct Permissions
    - name: Ensure .ssh directory exists for Hadoop user
      file:
        path: "/home/{{ hadoop_user }}/.ssh"
        state: directory
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
        mode: "0700"

    ## 游릭 Step 7: Generate SSH Key for Hadoop User (Fixed)
    - name: Generate SSH key pair manually
      command: ssh-keygen -t rsa -P '' -f /home/{{ hadoop_user }}/.ssh/id_rsa
      become: false  # Don't use sudo (Fixes permission issue)
      args:
        creates: /home/{{ hadoop_user }}/.ssh/id_rsa

    ## 游릭 Step 8: Add public key to authorized_keys
    - name: Add public key to authorized_keys
      shell: cat /home/{{ hadoop_user }}/.ssh/id_rsa.pub >> /home/{{ hadoop_user }}/.ssh/authorized_keys
      become: false
      args:
        creates: /home/{{ hadoop_user }}/.ssh/authorized_keys

    ## 游릭 Step 9: Set correct permissions on authorized_keys
    - name: Set correct permissions for authorized_keys
      file:
        path: "/home/{{ hadoop_user }}/.ssh/authorized_keys"
        mode: "0600"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
