---
- name: Télécharger un fichier avec curl
  hosts: all
  become: yes
  tasks:
    - name: Télécharger le fichier bundle avec curl
      expect:
        command: curl -LO https://k8s.kurl.sh/bundle/254c595.tar.gz
        responses:
          'Would you like to continue? [Y/n]': 'y'
