---
- name: Télécharger un fichier avec curl sur Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Forcer l'installation de curl
      apt:
        name: curl
        state: latest
        force: yes

    - name: Télécharger le fichier
      command: curl -LO https://k8s.kurl.sh/bundle/c64b8a9.tar.gz
      args:
        chdir: /tmp
