---
- name: Install Java, SSH, and configure Hadoop user
  hosts: all
  become: yes
  become_method: sudo
  vars:
    hadoop_user: "hdoop"
    hadoop_full_name: "hadoop"
    hadoop_password: "hadoop"
    hadoop_version: "3.4.0"
    ansible_ssh_pipelining: true

  pre_tasks:
    - name: Create temporary directory for Ansible
      file:
        path: /tmp/ansible-{{ hadoop_user }}
        state: directory
        mode: '0777'
      become: yes

    - name: Set allow_world_readable_tmpfiles
      set_fact:
        ansible_allow_world_readable_tmpfiles: true

  tasks:
    ## 游릭 Step 1: Update APT package lists
    - name: Update APT package lists
      apt:
        update_cache: yes
      become: yes

    ## 游릭 Step 2: Install OpenJDK 8
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
      become: yes

    ## 游릭 Step 3: Install OpenSSH Server & Client
    - name: Install OpenSSH Server & Client
      apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      become: yes

    ## 游릭 Step 4: Create Hadoop User
    - name: Create Hadoop User
      user:
        name: "{{ hadoop_user }}"
        comment: "{{ hadoop_full_name }}"
        password: "{{ hadoop_password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes
      become: yes

    ## 游릭 Step 5: Download and Install Hadoop
    - name: Download Hadoop
      get_url:
        url: "https://dlcdn.apache.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "/home/{{ hadoop_user }}/hadoop-{{ hadoop_version }}.tar.gz"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Extract Hadoop archive
      unarchive:
        src: "/home/{{ hadoop_user }}/hadoop-{{ hadoop_version }}.tar.gz"
        dest: "/home/{{ hadoop_user }}"
        remote_src: yes
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Move Hadoop to /usr/local
      command: "mv /home/{{ hadoop_user }}/hadoop-{{ hadoop_version }} /usr/local/hadoop"
      args:
        creates: "/usr/local/hadoop"
      become: yes

    ## 游릭 Step 6: Set up SSH for Hadoop user
    - name: Ensure .ssh directory exists
      file:
        path: "/home/{{ hadoop_user }}/.ssh"
        state: directory
        mode: '0700'
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      become: yes

    - name: Generate SSH Key
      command: "ssh-keygen -t rsa -b 4096 -f /home/{{ hadoop_user }}/.ssh/id_rsa -N ''"
      args:
        creates: "/home/{{ hadoop_user }}/.ssh/id_rsa"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Set up authorized_keys
      command: "cp /home/{{ hadoop_user }}/.ssh/id_rsa.pub /home/{{ hadoop_user }}/.ssh/authorized_keys"
      args:
        creates: "/home/{{ hadoop_user }}/.ssh/authorized_keys"
      become: yes
      become_user: "{{ hadoop_user }}"

    - name: Set correct permissions on SSH files
      file:
        path: "{{ item.path }}"
        mode: "{{ item.mode }}"
        owner: "{{ hadoop_user }}"
        group: "{{ hadoop_user }}"
      with_items:
        - { path: "/home/{{ hadoop_user }}/.ssh/authorized_keys", mode: '0600' }
        - { path: "/home/{{ hadoop_user }}/.ssh/id_rsa", mode: '0600' }
        - { path: "/home/{{ hadoop_user }}/.ssh/id_rsa.pub", mode: '0644' }
      become: yes
