---
- name: Installer kURL
  hosts: all
  become: yes
   tasks:
- name: Exécuter le script kURL
  expect:
    command: curl  https://kurl.sh/8eb26e2 | sudo bash 
    responses:
      'would you want to continue? [Y/n]': 'y' 
